[package]
name = "gcu-kernels"
version = "0.1.0"
edition = "2021"

description = "GCU kernels for Candle"
repository = "http://git.enflame.cn/era/candle-gcu.git"
categories = ["science"]
license = "MIT OR Apache-2.0"


[build-dependencies]
glob = "0.3.1"
