// Copyright 2025 LancerLab. All Rights Reserved.
// Licensed under the Apache License, Version 2.0.
// SPDX-License-Identifier: Apache-2.0
//
// Generated by Choreo (https://github.com/LancerLab/croqtile.git)
// Source: candle-croq-gdn/kernels/causal_conv1d.co
// Do not edit manually — regenerate with: choreo -gs -t topscc -arch=gcu300

#include <tops/tops_runtime.h>
#include <tcle.h>
#include "choreo_runtime.h"

using namespace choreo;

// GDN Production Causal Conv1d Kernel — full-featured replacement for ubridge
//
// Features:
//   - Multi-batch with per-slot cache_indices (PagedAttention slot mapping)
//   - Variable-length sequences via query_start_loc (cu_seqlens)
//   - Conv state read at start, write-back at end (decode continuity)
//   - has_initial_states flag per batch element
//   - Configurable SiLU activation
//   - Production dimensions: dim up to 6144, kernel_width=4, batch up to 2048
//   - Multi-SIP parallelism (N_BLK=2, N_SIP=12 for GCU3)
//
// Weight layout: [kernel_width, dim] — tap k at w_ptr[k * dim + c]
// Conv state layout: [batch, state_len, dim] where state_len = kernel_width - 1
// X layout: [total_tokens, dim] — packed sequences, boundaries in query_start_loc
//
// Based on causal_conv1d.co v254: register-preloaded weights, 2-step temporal
// reuse, acore::silu, dtu_vld_latency(22), native bf16 multiply.
//

#include <tops.h>
#include <tops/half.h>
#include <tops/bfloat.h>
#include <tops/tops_runtime.h>
#define KW          4
#define STATE_LEN   (KW - 1)

#define N_BLK       2
#define N_SIP       12
#define TOTAL_SIPS  (N_BLK * N_SIP)

#define BLOCK_N     256

#include <common/acore_op.h>

constexpr int VE = 128 / sizeof(__bf16);
using VB = __vector __bf16;

// Production conv1d compute: variable-length with state ring buffer.
//
// state_raw: [STATE_LEN, local_n] bf16 — conv state (read on entry, updated on exit)
// If has_state==0, state is treated as zeros.
// On exit, state contains the last STATE_LEN tokens for decode continuity.
__attribute__((no_mem_alias_in_vldst, no_mem_alias_in_tar,
               loop_iterator_less_than_1024, enable_bc_resolver,
               dtu_vld_latency(22)))
__co_device__ void conv_silu_bf16_prod(
    void* o_raw, void* x_raw, void* w_raw, void* bias_raw,
    void* state_raw, int n_time, int local_n, int has_state, int silu) {
    __bf16* o_ptr = reinterpret_cast<__bf16*>(o_raw);
    __bf16* x_ptr = reinterpret_cast<__bf16*>(x_raw);
    __bf16* w_ptr = reinterpret_cast<__bf16*>(w_raw);
    __bf16* bias_ptr = reinterpret_cast<__bf16*>(bias_raw);
    __bf16* st_ptr = reinterpret_cast<__bf16*>(state_raw);

    constexpr int MNV = BLOCK_N / VE;
    int nv = local_n / VE;

    VB* xv = reinterpret_cast<VB*>(x_ptr);
    VB* ov = reinterpret_cast<VB*>(o_ptr);

    // State ring buffer: st[0] = oldest (t-3), st[1] = t-2, st[2] = t-1
    // state_raw layout: [STATE_LEN][local_n]
    VB* sv0 = reinterpret_cast<VB*>(st_ptr + 0 * local_n);  // oldest (t-3 relative)
    VB* sv1 = reinterpret_cast<VB*>(st_ptr + 1 * local_n);  // t-2
    VB* sv2 = reinterpret_cast<VB*>(st_ptr + 2 * local_n);  // t-1 (newest state)

    // Preload all 4 weight taps into registers (reversed: w0=newest, w3=oldest)
    // Standard conv: tap k pairs with src_t = t-(KW-1)+k
    // w0 = tap[3] (applied to x[t]), w3 = tap[0] (applied to x[t-3])
    VB w0[MNV], w1[MNV], w2[MNV], w3[MNV];
    #pragma unroll
    for (int v = 0; v < MNV; v++) w0[v] = ((VB*)(w_ptr + 3*local_n))[v];
    #pragma unroll
    for (int v = 0; v < MNV; v++) w1[v] = ((VB*)(w_ptr + 2*local_n))[v];
    #pragma unroll
    for (int v = 0; v < MNV; v++) w2[v] = ((VB*)(w_ptr + 1*local_n))[v];
    #pragma unroll
    for (int v = 0; v < MNV; v++) w3[v] = ((VB*)(w_ptr + 0*local_n))[v];

    VB b[MNV];
    #pragma unroll
    for (int v = 0; v < MNV; v++) b[v] = ((VB*)bias_ptr)[v];

    // Load state into registers if has_state, else zero
    VB s0[MNV], s1[MNV], s2[MNV];
    if (has_state) {
        #pragma unroll
        for (int v = 0; v < MNV; v++) s0[v] = sv0[v];
        #pragma unroll
        for (int v = 0; v < MNV; v++) s1[v] = sv1[v];
        #pragma unroll
        for (int v = 0; v < MNV; v++) s2[v] = sv2[v];
    } else {
        VB zero = (VB)(__bf16)0.0f;
        #pragma unroll
        for (int v = 0; v < MNV; v++) { s0[v] = zero; s1[v] = zero; s2[v] = zero; }
    }

    // t=0: uses state s2(t-1), s1(t-2), s0(t-3)
    #pragma unroll
    for (int v = 0; v < MNV; v++)
        ov[v] = xv[v] * w0[v] + s2[v] * w1[v] + s1[v] * w2[v] + s0[v] * w3[v] + b[v];

    // t=1: uses x[0], state s2(t-1 of seq → state newest), s1
    if (n_time > 1) {
        #pragma unroll
        for (int v = 0; v < MNV; v++)
            ov[nv + v] = xv[nv + v] * w0[v] + xv[v] * w1[v] + s2[v] * w2[v] + s1[v] * w3[v] + b[v];
    }

    // t=2: uses x[1], x[0], state s2
    if (n_time > 2) {
        #pragma unroll
        for (int v = 0; v < MNV; v++)
            ov[2*nv + v] = xv[2*nv + v] * w0[v] + xv[nv + v] * w1[v]
                         + xv[v] * w2[v] + s2[v] * w3[v] + b[v];
    }

    // Main loop: fully within x[], 2-step temporal reuse
    #pragma unroll 3
    for (int t = 3; t < n_time; t += 2) {
        int b0 = t * nv;
        int b1 = (t + 1) * nv;
        #pragma unroll
        for (int v = 0; v < MNV; v++) {
            VB xt   = xv[b0 + v];
            VB xt_1 = xv[b0 - nv + v];
            VB xt_2 = xv[b0 - 2*nv + v];
            VB xt_3 = xv[b0 - 3*nv + v];
            ov[b0 + v] = xt * w0[v] + xt_1 * w1[v] + xt_2 * w2[v] + xt_3 * w3[v] + b[v];
            if (t + 1 < n_time) {
                VB xtp1 = xv[b1 + v];
                ov[b1 + v] = xtp1 * w0[v] + xt * w1[v] + xt_1 * w2[v] + xt_2 * w3[v] + b[v];
            }
        }
    }

    // Write back last STATE_LEN tokens to state buffer for decode continuity.
    // After processing, state should contain the last 3 tokens of the sequence.
    if (n_time >= 3) {
        int last = n_time - 1;
        #pragma unroll
        for (int v = 0; v < MNV; v++) {
            sv0[v] = xv[(last - 2) * nv + v];
            sv1[v] = xv[(last - 1) * nv + v];
            sv2[v] = xv[last * nv + v];
        }
    } else if (n_time == 2) {
        // Only 2 new tokens: shift state and append
        #pragma unroll
        for (int v = 0; v < MNV; v++) {
            sv0[v] = s2[v];           // old newest becomes oldest
            sv1[v] = xv[v];           // first token
            sv2[v] = xv[nv + v];      // second token
        }
    } else if (n_time == 1) {
        // Single token: shift state
        #pragma unroll
        for (int v = 0; v < MNV; v++) {
            sv0[v] = s1[v];
            sv1[v] = s2[v];
            sv2[v] = xv[v];
        }
    }

    if (silu)
        acore::silu<__bf16, __bf16>(o_ptr, o_ptr, n_time * local_n);
}
// Compile-time max tile for local memory sizing.  Actual seqlen can be shorter.
#define MAX_TILE_T  64
__global__ void __choreo_device_causal_conv1d_fwd_bf16_prod(choreo::bf16 * X, choreo::bf16 * W, choreo::bf16 * Bias, choreo::bf16 * St, int64_t * CacheIdx, unsigned int * QSL, choreo::bf16 * Out, bool silu, unsigned BATCH, unsigned BATCH_P1, unsigned DIM_G, unsigned MAX_BATCH, unsigned TOTAL_TOKENS) {
  choreo::choreo_sdte __choreo_dte_pool__[4];
  for (int __i = 0; __i < 4; ++__i) __choreo_dte_pool__[__i].init();
  { // parallel-by: 198.24
  __local__ __valigned__ unsigned char anon_3[69632];
  int sip_id = __tops_tid_x() * 2 + __tops_bid_x();
  int ch_blocks = ((DIM_G + 255) / 256);
  int total_work = (BATCH * ch_blocks);
  int work_per_sip = ((total_work + 23) / 24);
  int silu_val = (silu ? 1 : 0);
  // with-in: 208.9
  {
    int __iv_wi__elem__0 = 0;
    // foreach: 208.9
    for (__iv_wi__elem__0 = 0; __iv_wi__elem__0 < work_per_sip; ++__iv_wi__elem__0) {
      int work_id = (sip_id * work_per_sip) + __iv_wi__elem__0;
      // inthreads: 210.13
      if ((work_id < total_work)) {
        int seq_idx = (work_id / ch_blocks);
        int ch_block = (work_id % ch_blocks);
        int feat_start = (ch_block * 256);
        int actual_n = 256;
        // inthreads: 215.17
        if ((feat_start + 256 > DIM_G)) {
          actual_n = (DIM_G - feat_start);
        } // end inthreads
        int64_t* cidx_f__buf__ = (int64_t*)(anon_3 + 0);
        choreo::future cidx_f(__choreo_dte_pool__[0], "cidx_f", 219, 26, cidx_f__buf__);
        tops::mdspan __mds0_CacheIdx(tops::Global, (char*)CacheIdx, BATCH, 8);
        tops::mdspan __mds1_cidx_f__buf__(tops::Private, (char*)cidx_f__buf__, 1, 8);
        int __slice_offset0__CacheIdx_2_cidx_f__buf__[] = {(int)(seq_idx), 0};
        tops::event cidx_f__event__ = tops::slice_async(*cidx_f.get_ctx(), __mds1_cidx_f__buf__, __mds0_CacheIdx, __slice_offset0__CacheIdx_2_cidx_f__buf__);
        cidx_f.set_event(cidx_f__event__);
        unsigned int* cu_start_f__buf__ = (unsigned int*)(anon_3 + 1024);
        choreo::future cu_start_f(__choreo_dte_pool__[1], "cu_start_f", 220, 30, cu_start_f__buf__);
        tops::mdspan __mds2_QSL(tops::Global, (unsigned int*)QSL, BATCH_P1);
        tops::mdspan __mds3_cu_start_f__buf__(tops::Private, (unsigned int*)cu_start_f__buf__, 1);
        int __slice_offset1__QSL_2_cu_start_f__buf__[] = {(int)(seq_idx)};
        tops::event cu_start_f__event__ = tops::slice_async(*cu_start_f.get_ctx(), __mds3_cu_start_f__buf__, __mds2_QSL, __slice_offset1__QSL_2_cu_start_f__buf__);
        cu_start_f.set_event(cu_start_f__event__);
        auto anon_0 = (seq_idx + 1);
        unsigned int* cu_end_f__buf__ = (unsigned int*)(anon_3 + 512);
        choreo::future cu_end_f(__choreo_dte_pool__[2], "cu_end_f", 221, 28, cu_end_f__buf__);
        tops::mdspan __mds4_QSL(tops::Global, (unsigned int*)QSL, BATCH_P1);
        tops::mdspan __mds5_cu_end_f__buf__(tops::Private, (unsigned int*)cu_end_f__buf__, 1);
        int __slice_offset2__QSL_2_cu_end_f__buf__[] = {(int)(anon_0)};
        tops::event cu_end_f__event__ = tops::slice_async(*cu_end_f.get_ctx(), __mds5_cu_end_f__buf__, __mds4_QSL, __slice_offset2__QSL_2_cu_end_f__buf__);
        cu_end_f.set_event(cu_end_f__event__);
        cidx_f.wait();
        cu_start_f.wait();
        cu_end_f.wait();
        int cidx = static_cast<int>(*((int64_t*)cidx_f.data() + 0));
        int start = static_cast<int>(*((unsigned int*)cu_start_f.data() + 0));
        int end_t = static_cast<int>(*((unsigned int*)cu_end_f.data() + 0));
        int seqlen = (end_t - start);
        choreo::bfloat16* l_wt = (choreo::bfloat16*)(anon_3 + 65536);
        choreo::future __choreo_anon_fut__0(__choreo_dte_pool__[0], "", 230, 17, l_wt);
        if ((DIM_G * 3 + 256 == 1024)) {
          tops::mdspan __mds6_W(tops::Global, (choreo::bfloat16*)W, 4, DIM_G);
          tops::mdspan __mds7_l_wt(tops::Private, (choreo::bfloat16*)l_wt, 4, 256);
          int __slice_offset3__W_2_l_wt[] = {0, (int)((ch_block * 256))};
          tops::slice(*__choreo_anon_fut__0.get_ctx(), __mds7_l_wt, __mds6_W, __slice_offset3__W_2_l_wt);
        } else {
          tops::mdspan __mds8_W(tops::Global, (choreo::bfloat16*)W, 4, DIM_G);
          tops::mdspan __mds9_l_wt(tops::Private, (choreo::bfloat16*)l_wt, 4, 256);
          int __slice_offset4__W_2_l_wt[] = {0, (int)((ch_block * 256))};
          tops::slice(*__choreo_anon_fut__0.get_ctx(), __mds9_l_wt, __mds8_W, __slice_offset4__W_2_l_wt);
        } // end DMA opt: 230.17
        choreo::bfloat16* l_bias = (choreo::bfloat16*)(anon_3 + 69120);
        choreo::future __choreo_anon_fut__1(__choreo_dte_pool__[0], "", 233, 17, l_bias);
        tops::mdspan __mds10_Bias(tops::Global, (choreo::bfloat16*)Bias, DIM_G);
        tops::mdspan __mds11_l_bias(tops::Private, (choreo::bfloat16*)l_bias, 256);
        int __slice_offset5__Bias_2_l_bias[] = {(int)((ch_block * 256))};
        tops::slice(*__choreo_anon_fut__1.get_ctx(), __mds11_l_bias, __mds10_Bias, __slice_offset5__Bias_2_l_bias);
        choreo::bfloat16* l_state = (choreo::bfloat16*)(anon_3 + 67584);
        choreo::future state_f(__choreo_dte_pool__[3], "state_f", 236, 27, l_state);
        if ((DIM_G * 2 + 256 == 768)) {
          tops::mdspan __mds12_St(tops::Global, (choreo::bfloat16*)St, MAX_BATCH, 3, DIM_G);
          tops::mdspan __mds13_l_state(tops::Private, (choreo::bfloat16*)l_state, 1, 3, 256);
          int __slice_offset6__St_2_l_state[] = {(int)(cidx), 0, (int)((ch_block * 256))};
          tops::event state_f__event__ = tops::slice_async(*state_f.get_ctx(), __mds13_l_state, __mds12_St, __slice_offset6__St_2_l_state);
          state_f.set_event(state_f__event__);
        } else {
          tops::mdspan __mds14_St(tops::Global, (choreo::bfloat16*)St, MAX_BATCH, 3, DIM_G);
          tops::mdspan __mds15_l_state(tops::Private, (choreo::bfloat16*)l_state, 1, 3, 256);
          int __slice_offset7__St_2_l_state[] = {(int)(cidx), 0, (int)((ch_block * 256))};
          tops::event state_f__event__ = tops::slice_async(*state_f.get_ctx(), __mds15_l_state, __mds14_St, __slice_offset7__St_2_l_state);
          state_f.set_event(state_f__event__);
        } // end DMA opt: 236.27
        state_f.wait();
        choreo::bfloat16* l_x = (choreo::bfloat16*)(anon_3 + 32768);
        choreo::bfloat16* l_out = (choreo::bfloat16*)(anon_3 + 0);
        int n_chunks = ((seqlen + 63) / 64);
        int offset = 0;
        // with-in: 244.17
        {
          int __iv__chunk__elem__0 = 0;
          // foreach: 244.17
          for (__iv__chunk__elem__0 = 0; __iv__chunk__elem__0 < n_chunks; ++__iv__chunk__elem__0) {
            int chunk_len = (seqlen - offset);
            // if-else: 246.21
            if ((chunk_len > 64)) {
              chunk_len = 64;
            } // end if-else: 246.21
            // with-in: 248.21
            {
              int __iv_it__elem__0 = 0;
              // foreach: 248.21
              for (__iv_it__elem__0 = 0; __iv_it__elem__0 < chunk_len; ++__iv_it__elem__0) {
                auto anon_1 = (offset + start) + __iv_it__elem__0;
                choreo::future __choreo_anon_fut__2(__choreo_dte_pool__[0], "", 249, 25, l_x);
                tops::mdspan __mds16_X(tops::Global, (choreo::bfloat16*)X, TOTAL_TOKENS, DIM_G);
                tops::mdspan __mds17_l_x(tops::Private, (choreo::bfloat16*)l_x, 64, 256);
                int __slice_offset0__X_2_l_x[] = {(int)(anon_1), (int)((ch_block * 256))};
                int __deslice_offset0__l_x_2_X[] = {(int)(__iv_it__elem__0), 0};
                unsigned int __slice_shape1__X_2_l_x[] = {1, 256};
                tops::slice_deslice(*__choreo_anon_fut__2.get_ctx(), __mds17_l_x, __mds16_X, __slice_offset0__X_2_l_x, __slice_shape1__X_2_l_x, __deslice_offset0__l_x_2_X);
              } // it__elem__0
              __iv_it__elem__0 = 0;
            }
            conv_silu_bf16_prod((choreo::bf16*)l_out, (choreo::bf16*)l_x, (choreo::bf16*)l_wt, (choreo::bf16*)l_bias, (choreo::bf16*)l_state, chunk_len, actual_n, 1, silu_val);
            // with-in: 256.21
            {
              int __iv_ot__elem__0 = 0;
              // foreach: 256.21
              for (__iv_ot__elem__0 = 0; __iv_ot__elem__0 < chunk_len; ++__iv_ot__elem__0) {
                auto anon_2 = (offset + start) + __iv_ot__elem__0;
                choreo::future __choreo_anon_fut__3(__choreo_dte_pool__[0], "", 257, 25, Out);
                tops::mdspan __mds18_l_out(tops::Private, (choreo::bfloat16*)l_out, 64, 256);
                tops::mdspan __mds19_Out(tops::Global, (choreo::bfloat16*)Out, TOTAL_TOKENS, DIM_G);
                int __slice_offset1__l_out_2_Out[] = {(int)(__iv_ot__elem__0), 0};
                int __deslice_offset1__Out_2_l_out[] = {(int)(anon_2), (int)((ch_block * 256))};
                unsigned int __slice_shape2__l_out_2_Out[] = {1, 256};
                tops::slice_deslice(*__choreo_anon_fut__3.get_ctx(), __mds19_Out, __mds18_l_out, __slice_offset1__l_out_2_Out, __slice_shape2__l_out_2_Out, __deslice_offset1__Out_2_l_out);
              } // ot__elem__0
              __iv_ot__elem__0 = 0;
            }
            offset = (offset + chunk_len);
          } // _chunk__elem__0
          __iv__chunk__elem__0 = 0;
        }
        choreo::future __choreo_anon_fut__4(__choreo_dte_pool__[0], "", 263, 17);
        if ((DIM_G * 2 + 256 == 768)) {
          tops::mdspan __mds20_l_state(tops::Private, (choreo::bfloat16*)l_state, 1, 3, 256);
          tops::mdspan __mds21_St(tops::Global, (choreo::bfloat16*)St, MAX_BATCH, 3, DIM_G);
          int __deslice_offset0__St_2_l_state[] = {(int)(cidx), 0, (int)((ch_block * 256))};
          tops::deslice(*__choreo_anon_fut__4.get_ctx(), __mds21_St, __mds20_l_state, __deslice_offset0__St_2_l_state);
        } else {
          tops::mdspan __mds22_l_state(tops::Private, (choreo::bfloat16*)l_state, 1, 3, 256);
          tops::mdspan __mds23_St(tops::Global, (choreo::bfloat16*)St, MAX_BATCH, 3, DIM_G);
          int __deslice_offset1__St_2_l_state[] = {(int)(cidx), 0, (int)((ch_block * 256))};
          tops::deslice(*__choreo_anon_fut__4.get_ctx(), __mds23_St, __mds22_l_state, __deslice_offset1__St_2_l_state);
        } // end DMA opt: 263.17
      }
      __syncthreads(); // end inthreads
    } // wi__elem__0
    __iv_wi__elem__0 = 0;
  }
  } // end parallel-by
}

void causal_conv1d_fwd_bf16_prod(const choreo::spanned_view<choreo::bf16, 2> & X, const choreo::spanned_view<choreo::bf16, 2> & W, const choreo::spanned_view<choreo::bf16, 1> & Bias, const choreo::spanned_view<choreo::bf16, 3> & St, const choreo::spanned_view<choreo::s64, 1> & CacheIdx, const choreo::spanned_view<choreo::u32, 1> & QSL, const choreo::spanned_view<choreo::bf16, 2> & Out, bool silu, choreo::stream_t _s) {
  auto &BATCH = CacheIdx.shape()[0];
  auto &BATCH_P1 = QSL.shape()[0];
  auto &DIM_G = X.shape()[1];
  auto &MAX_BATCH = St.shape()[0];
  auto &TOTAL_TOKENS = X.shape()[0];
  choreo::runtime_check(W.shape()[0] == 4, "shape inconsistent on the 2nd parameter ('W', dim: 0): expect: 4, but got " + std::to_string(W.shape()[0]) + ".");
  choreo::runtime_check(St.shape()[1] == 3, "shape inconsistent on the 4th parameter ('St', dim: 1): expect: 3, but got " + std::to_string(St.shape()[1]) + ".");
  choreo::runtime_check(X.shape()[1] == W.shape()[1], "The shapes of the 1st parameter (dim: 1) and the 2nd parameter (dim: 1) are inconsistent.");
  choreo::runtime_check(W.shape()[1] == Bias.shape()[0], "The shapes of the 2nd parameter (dim: 1) and the 3rd parameter (dim: 0) are inconsistent.");
  choreo::runtime_check(Bias.shape()[0] == St.shape()[2], "The shapes of the 3rd parameter (dim: 0) and the 4th parameter (dim: 2) are inconsistent.");
  choreo::runtime_check(St.shape()[2] == Out.shape()[1], "The shapes of the 4th parameter (dim: 2) and the 7th parameter (dim: 1) are inconsistent.");
  choreo::runtime_check(X.shape()[0] == Out.shape()[0], "The shapes of the 1st parameter (dim: 0) and the 7th parameter (dim: 0) are inconsistent.");

  choreo::runtime_check((static_cast<long long>(BATCH) * 8LL < 4294967296LL), "The size of data transferred by DMA cannot exceed 2^32., 219.26");
  choreo::runtime_check((static_cast<long long>(BATCH_P1) * 4LL < 4294967296LL), "The size of data transferred by DMA cannot exceed 2^32., 220.30");
  choreo::runtime_check((static_cast<long long>(BATCH_P1) * 4LL < 4294967296LL), "The size of data transferred by DMA cannot exceed 2^32., 221.28");
  dim3 __causal_conv1d_fwd_bf16_prod_gdims0(2, 1, 1);
  dim3 __causal_conv1d_fwd_bf16_prod_bdims0(12, 1, 1);
  __choreo_device_causal_conv1d_fwd_bf16_prod<<<__causal_conv1d_fwd_bf16_prod_gdims0, __causal_conv1d_fwd_bf16_prod_bdims0, 0, _s>>>(X.data(), W.data(), Bias.data(), St.data(), CacheIdx.data(), QSL.data(), Out.data(), silu, BATCH, BATCH_P1, DIM_G, MAX_BATCH, TOTAL_TOKENS);
}
// CPU reference: multi-batch variable-length causal conv1d with state

// === Wrapper: raw pointers → spanned_view ===
extern "C" void causal_conv1d_fwd_bf16_prod_wrapper(
    void* x, void* w, void* bias, void* conv_states,
    int64_t* cache_indices,
    uint32_t* query_start_loc, void* out,
    bool silu,
    int total_tokens, int dim, int batch, int kw,
    int max_batch,
    void* stream) {

    topsStream_t s = reinterpret_cast<topsStream_t>(stream);
    int state_len = kw - 1;

    auto x_sv = croq::make_spanview<2, croq::bf16>(
        (croq::bf16*)x, {(size_t)total_tokens, (size_t)dim});
    auto w_sv = croq::make_spanview<2, croq::bf16>(
        (croq::bf16*)w, {(size_t)kw, (size_t)dim});
    auto bias_sv = croq::make_spanview<1, croq::bf16>(
        (croq::bf16*)bias, {(size_t)dim});
    auto state_sv = croq::make_spanview<3, croq::bf16>(
        (croq::bf16*)conv_states, {(size_t)max_batch, (size_t)state_len, (size_t)dim});
    auto cidx_sv = croq::make_spanview<1, int64_t>(
        cache_indices, {(size_t)batch});
    auto qsl_sv = croq::make_spanview<1, uint32_t>(
        query_start_loc, {(size_t)(batch + 1)});
    auto out_sv = croq::make_spanview<2, croq::bf16>(
        (croq::bf16*)out, {(size_t)total_tokens, (size_t)dim});

    causal_conv1d_fwd_bf16_prod(
        x_sv, w_sv, bias_sv, state_sv,
        cidx_sv, qsl_sv, out_sv,
        silu, s);
}
