// Copyright 2025 LancerLab. All Rights Reserved.
// Licensed under the Apache License, Version 2.0.
// SPDX-License-Identifier: Apache-2.0
//
// Generated by Choreo (https://github.com/LancerLab/croqtile.git)
// Source: candle-croq-gdn/kernels/gdn_l2norm.co
// Do not edit manually — regenerate with: choreo -gs -t topscc -arch=gcu300

#include <tops.h>
#include <tops/half.h>
#include <tops/bfloat.h>
#include <tops/tops_runtime.h>
#include <tops/topscc_types.h>
#include <tcle.h>
#include "choreo_runtime.h"

using namespace choreo;

using vf = __vector4 float;
using vb = __vector2 __bf16;

__co_device__ void l2norm_vec_inplace(void* buf_v, float eps) {
    __bf16* buf = (__bf16*)buf_v;

    vb raw = *(vb*)buf;
    vf xf = tcle::cvt<vf>(raw);

    vf sq = xf * xf;
    float sum_sq = tops::vreduce_sum<float>(sq);
    float inv_norm = tcle::rsqrt(sum_sq + eps);
    vf result = xf * (vf)(inv_norm);

    *(vb*)buf = tcle::cvt<vb>(result);
}

__global__ void __choreo_device_gdn_l2_norm_bf16(choreo::bf16 * Input, choreo::bf16 * Output, unsigned DIM, unsigned ROWS, unsigned long mr_offset_gdn_l2_norm_bf16_paraby_0_paraby_1_in_chunk) {
  choreo::choreo_sdte __choreo_dte_pool__[2];
  for (int __i = 0; __i < 2; ++__i) __choreo_dte_pool__[__i].init();
  { // parallel-by: 51.18
  __local__ __valigned__ unsigned char anon_0[1572352];
  int sip_id = __tops_tid_x() * 2 + __tops_bid_x();
  int rows_per_sip = ((ROWS + 23) / 24);
  choreo::bfloat16* in_chunk = (choreo::bfloat16*)(anon_0 + mr_offset_gdn_l2_norm_bf16_paraby_0_paraby_1_in_chunk);
  int chunks_per_sip = ((rows_per_sip + 31) / 32);
  // with-in: 59.9
  {
    int __iv_chunk_idx__elem__0 = 0;
    // foreach: 59.9
    for (__iv_chunk_idx__elem__0 = 0; __iv_chunk_idx__elem__0 < chunks_per_sip; ++__iv_chunk_idx__elem__0) {
      int base_row = (rows_per_sip * sip_id) + __iv_chunk_idx__elem__0 * 32;
      int chunk_rows = rows_per_sip - __iv_chunk_idx__elem__0 * 32;
      // if-else: 62.13
      if ((chunk_rows > 32)) {
        chunk_rows = 32;
      } // end if-else: 62.13
      // inthreads: 64.13
      if ((base_row < ROWS)) {
        // if-else: 65.17
        if ((base_row + chunk_rows > ROWS)) {
          chunk_rows = (ROWS - base_row);
        } // end if-else: 65.17
        choreo::future l(__choreo_dte_pool__[0], "l", 67, 21, in_chunk);
        tops::mdspan __mds0_Input(tops::Global, (choreo::bfloat16*)Input, ROWS, DIM);
        tops::mdspan __mds1_in_chunk(tops::Private, (choreo::bfloat16*)in_chunk, 32, DIM);
        int __slice_offset0__Input_2_in_chunk[] = {(int)(base_row), 0};
        int __deslice_offset0__in_chunk_2_Input[] = {0, 0};
        unsigned int __slice_shape1__Input_2_in_chunk[] = {static_cast<unsigned int>(chunk_rows), static_cast<unsigned int>(DIM)};
        tops::event l__event__ = tops::slice_deslice_async(*l.get_ctx(), __mds1_in_chunk, __mds0_Input, __slice_offset0__Input_2_in_chunk, __slice_shape1__Input_2_in_chunk, __deslice_offset0__in_chunk_2_Input);
        l.set_event(l__event__);
        l.wait();
        // with-in: 70.17
        {
          int __iv_r__elem__0 = 0;
          // foreach: 70.17
          for (__iv_r__elem__0 = 0; __iv_r__elem__0 < chunk_rows; ++__iv_r__elem__0) {
            l2norm_vec_inplace((choreo::bf16*)in_chunk + (DIM * __iv_r__elem__0), 0.000001f);
          } // r__elem__0
          __iv_r__elem__0 = 0;
        }
        choreo::future __choreo_anon_fut__0(__choreo_dte_pool__[1], "", 76, 17, Output);
        tops::mdspan __mds2_in_chunk(tops::Private, (choreo::bfloat16*)in_chunk, 32, DIM);
        tops::mdspan __mds3_Output(tops::Global, (choreo::bfloat16*)Output, ROWS, DIM);
        int __slice_offset1__in_chunk_2_Output[] = {0, 0};
        int __deslice_offset1__Output_2_in_chunk[] = {(int)(base_row), 0};
        unsigned int __slice_shape2__in_chunk_2_Output[] = {static_cast<unsigned int>(chunk_rows), static_cast<unsigned int>(DIM)};
        tops::slice_deslice(*__choreo_anon_fut__0.get_ctx(), __mds3_Output, __mds2_in_chunk, __slice_offset1__in_chunk_2_Output, __slice_shape2__in_chunk_2_Output, __deslice_offset1__Output_2_in_chunk);
      }
      __syncthreads(); // end inthreads
    } // chunk_idx__elem__0
    __iv_chunk_idx__elem__0 = 0;
  }
  } // end parallel-by
}

void gdn_l2_norm_bf16(const choreo::spanned_view<choreo::bf16, 2> & Input, const choreo::spanned_view<choreo::bf16, 2> & Output, choreo::stream_t _s) {
  auto &DIM = Input.shape()[1];
  auto &ROWS = Input.shape()[0];

  HeapSimulator::Chunks __co__local_chunks;
  __co__local_chunks.push_back({static_cast<size_t>((DIM * 2)), {{5,15}}, "_gdn_l2_norm_bf16_paraby_0_paraby_1_l_in"});
  HeapSimulator __co_local_heap_simulator;
  HeapSimulator::Result __co__local_result = __co_local_heap_simulator.Allocate(__co__local_chunks, 512);
  unsigned __co__local_spm_size = __co__local_result.heap_size;
  unsigned long __co__local_chunk_offsets[1];
  size_t __co__local_chunks_idx = 0;
  for (const auto& [buffer_id, offset] : __co__local_result.chunk_offsets)
    __co__local_chunk_offsets[__co__local_chunks_idx++] = offset;
  dim3 __gdn_l2_norm_bf16_gdims0(2, 1, 1);
  dim3 __gdn_l2_norm_bf16_bdims0(12, 1, 1);
  __choreo_device_gdn_l2_norm_bf16<<<__gdn_l2_norm_bf16_gdims0, __gdn_l2_norm_bf16_bdims0, 0, _s>>>(Input.data(), Output.data(), DIM, ROWS, __co__local_chunk_offsets[0]);
}

extern "C" void gdn_l2_norm_bf16_wrapper(
    void* input, void* output,
    int rows, int dim, topsStream_t stream) {
  auto in_sv = croq::make_spanview<2, croq::bf16>(
      (croq::bf16*)input, {(size_t)rows, (size_t)dim});
  auto out_sv = croq::make_spanview<2, croq::bf16>(
      (croq::bf16*)output, {(size_t)rows, (size_t)dim});
  gdn_l2_norm_bf16(in_sv, out_sv, stream);
}
