// Copyright 2025 LancerLab. All Rights Reserved.
// Licensed under the Apache License, Version 2.0.
// SPDX-License-Identifier: Apache-2.0
//
// GDN FFI Bridge — extern "C" entry points for Rust FFI (ffi.rs).
//
// Maps typed C pointers from Rust into the Choreo wrapper functions
// defined in the individual *_host.cpp kernel files.
// Choreo kernels generated by: https://github.com/LancerLab/croqtile.git

#include <tops.h>
#include <tops/half.h>
#include <tops/bfloat.h>
#include <tops/tops_runtime.h>
#include <cstdint>

// ========================================================================
// Wrapper declarations (defined in *_host.cpp files)
// ========================================================================

extern "C" void gdn_recurrence_bf16_wrapper(
    void* q, void* k, void* v,
    float* g, float* beta, float* state, float* out,
    int bh, int seq_len, int k_dim, int v_dim, void* stream);

extern "C" void gdn_decode_slots_bf16_wrapper(
    void* q, void* k, void* v,
    float* g, float* beta,
    float* state, int64_t* slots, float* out,
    int batch, int heads, int k_dim, int v_dim,
    int max_slots, void* stream);

extern "C" void gdn_recurrence_varlen_bf16_wrapper(
    void* q, void* k, void* v,
    void* g, void* beta,
    float* state, int64_t* slots, void* out, uint32_t* cu_seqlens,
    int total_tokens, int batch, int num_k_heads, int num_v_heads,
    int max_slots, int k_dim, int v_dim, void* stream);

extern "C" void gdn_fused_gating_bf16_wrapper(
    void* a_log, void* a, void* b, void* dt_bias,
    void* g, void* beta,
    int total, int num_heads, void* stream);

extern "C" void gdn_l2_norm_bf16_wrapper(
    void* input, void* output,
    int rows, int dim, void* stream);

extern "C" void gdn_gated_rmsnorm_bf16_wrapper(
    void* x, void* z, void* gamma, void* out,
    int rows, int dim, void* stream);

extern "C" void causal_conv1d_fwd_bf16_prod_wrapper(
    void* x, void* w, void* bias, void* conv_states,
    int64_t* cache_indices,
    uint32_t* query_start_loc, void* out,
    bool silu,
    int total_tokens, int dim, int batch, int kw,
    int max_batch,
    void* stream);

// ========================================================================
// BF16 recurrence (prefill, fixed-length)
// ========================================================================

extern "C" void gdn_recurrence_bf16(
    const __bf16* q, const __bf16* k, const __bf16* v,
    const float* g, const float* beta, float* state, float* out,
    int bh, int seq_len, int k_dim, int v_dim,
    unsigned int num_blocks, unsigned int dim_blocks, void* stream_) {
    gdn_recurrence_bf16_wrapper(
        (void*)q, (void*)k, (void*)v,
        (float*)g, (float*)beta, state, out,
        bh, seq_len, k_dim, v_dim, stream_);
}

// ========================================================================
// BF16 decode slots (batched, slot-aware)
// ========================================================================

extern "C" void gdn_decode_slots_bf16(
    const __bf16* q, const __bf16* k, const __bf16* v,
    const float* g, const float* beta,
    float* state, const int64_t* slots_i64, float* out,
    int batch, int heads, int k_dim, int v_dim,
    int max_slots,
    unsigned int num_blocks, unsigned int dim_blocks, void* stream_) {
    gdn_decode_slots_bf16_wrapper(
        (void*)q, (void*)k, (void*)v,
        (float*)g, (float*)beta,
        state, (int64_t*)slots_i64, out,
        batch, heads, k_dim, v_dim, max_slots,
        stream_);
}

// ========================================================================
// BF16 varlen recurrence (prefill, variable-length with slot DMA)
// ========================================================================

extern "C" void gdn_recurrence_varlen_bf16(
    const __bf16* q, const __bf16* k, const __bf16* v,
    const __bf16* g, const __bf16* beta,
    float* state, const int64_t* slots_i64,
    __bf16* out, const uint32_t* cu_seqlens,
    int total_tokens, int batch, int num_heads, int k_dim, int v_dim,
    int max_slots,
    unsigned int num_blocks, unsigned int dim_blocks, void* stream_) {
    if (total_tokens == 0) return;
    gdn_recurrence_varlen_bf16_wrapper(
        (void*)q, (void*)k, (void*)v,
        (void*)g, (void*)beta,
        state, (int64_t*)slots_i64, (void*)out, (uint32_t*)cu_seqlens,
        total_tokens, batch, num_heads, num_heads,
        max_slots, k_dim, v_dim, stream_);
}

extern "C" void gdn_recurrence_varlen_gqa_bf16(
    const __bf16* q, const __bf16* k, const __bf16* v,
    const __bf16* g, const __bf16* beta,
    float* state, const int64_t* slots_i64,
    __bf16* out, const uint32_t* cu_seqlens,
    int total_tokens, int batch, int num_k_heads, int num_v_heads,
    int k_dim, int v_dim, int max_slots,
    unsigned int num_blocks, unsigned int dim_blocks, void* stream_) {
    if (total_tokens == 0) return;
    gdn_recurrence_varlen_bf16_wrapper(
        (void*)q, (void*)k, (void*)v,
        (void*)g, (void*)beta,
        state, (int64_t*)slots_i64, (void*)out, (uint32_t*)cu_seqlens,
        total_tokens, batch, num_k_heads, num_v_heads,
        max_slots, k_dim, v_dim, stream_);
}

// ========================================================================
// BF16 fused gating
// ========================================================================

extern "C" void gdn_fused_gating_bf16(
    const float* a_log, const __bf16* a, const __bf16* b, const float* dt_bias,
    __bf16* g, __bf16* beta,
    int total, int num_heads, void* stream) {
    if (total == 0) return;
    gdn_fused_gating_bf16_wrapper(
        (void*)a_log, (void*)a, (void*)b, (void*)dt_bias,
        (void*)g, (void*)beta,
        total, num_heads, stream);
}

// ========================================================================
// BF16 L2 normalization
// ========================================================================

extern "C" void gdn_l2_norm_bf16(
    const __bf16* input, __bf16* output,
    int rows, int dim, void* stream) {
    if (rows == 0) return;
    gdn_l2_norm_bf16_wrapper(
        (void*)input, (void*)output,
        rows, dim, stream);
}

// ========================================================================
// BF16 gated RMSNorm + SiLU
// ========================================================================

extern "C" void gdn_gated_rmsnorm_bf16(
    const __bf16* x, const __bf16* z, const float* gamma,
    __bf16* out, int rows, int dim, void* stream) {
    if (rows == 0) return;
    gdn_gated_rmsnorm_bf16_wrapper(
        (void*)x, (void*)z, (void*)gamma, (void*)out,
        rows, dim, stream);
}

// ========================================================================
// BF16 causal conv1d (unified prefill + decode)
// ========================================================================

static __bf16* s_prod_zero_bias = nullptr;
static int s_prod_zero_bias_dim = 0;

static __bf16* ensure_zero_bias(int d_conv) {
    if (s_prod_zero_bias && s_prod_zero_bias_dim >= d_conv) return s_prod_zero_bias;
    if (s_prod_zero_bias) topsFree(s_prod_zero_bias);
    topsMalloc((void**)&s_prod_zero_bias, d_conv * sizeof(__bf16));
    topsMemset(s_prod_zero_bias, 0, d_conv * sizeof(__bf16));
    s_prod_zero_bias_dim = d_conv;
    return s_prod_zero_bias;
}

extern "C" void causal_conv1d_fwd_choreo_bf16(
    const __bf16* x, const __bf16* weight, const __bf16* bias,
    __bf16* conv_state, const int64_t* cache_idx, const uint32_t* qsl,
    __bf16* out,
    int total_tokens, int d_conv, int batch, int kernel_size,
    int silu_activation, int max_slots, void* stream_) {
    const __bf16* bias_ptr = bias ? bias : ensure_zero_bias(d_conv);
    causal_conv1d_fwd_bf16_prod_wrapper(
        (void*)x, (void*)weight, (void*)bias_ptr, (void*)conv_state,
        (int64_t*)cache_idx, (uint32_t*)qsl, (void*)out,
        (silu_activation != 0),
        total_tokens, d_conv, batch, kernel_size, max_slots, stream_);
}

// ========================================================================
// F32/F16 stubs (not yet ported to Choreo)
// ========================================================================

extern "C" void gdn_recurrence_f32(
    const float*, const float*, const float*,
    const float*, const float*, float*, float*,
    int, int, int, int, unsigned int, unsigned int, void*) {}
extern "C" void gdn_recurrence_f16(
    const __fp16*, const __fp16*, const __fp16*,
    const float*, const float*, float*, float*,
    int, int, int, int, unsigned int, unsigned int, void*) {}

extern "C" void gdn_decode_slots_f32(
    const float*, const float*, const float*,
    const float*, const float*,
    float*, const int64_t*, float*,
    int, int, int, int, int, unsigned int, unsigned int, void*) {}
extern "C" void gdn_decode_slots_f16(
    const __fp16*, const __fp16*, const __fp16*,
    const __fp16*, const __fp16*,
    float*, const int64_t*, __fp16*,
    int, int, int, int, int, unsigned int, unsigned int, void*) {}

extern "C" void gdn_recurrence_varlen_f32(
    const float*, const float*, const float*,
    const float*, const float*,
    float*, const int64_t*,
    float*, const uint32_t*,
    int, int, int, int, int, int, unsigned int, unsigned int, void*) {}
extern "C" void gdn_recurrence_varlen_f16(
    const __fp16*, const __fp16*, const __fp16*,
    const __fp16*, const __fp16*,
    float*, const int64_t*,
    __fp16*, const uint32_t*,
    int, int, int, int, int, int, unsigned int, unsigned int, void*) {}

extern "C" void gdn_fused_gating_f32(
    const float*, const float*, const float*, const float*,
    float*, float*, int, int, unsigned int, unsigned int, void*) {}
extern "C" void gdn_fused_gating_f16(
    const float*, const __fp16*, const __fp16*, const float*,
    __fp16*, __fp16*, int, int, unsigned int, unsigned int, void*) {}

extern "C" void gdn_l2_norm_f32(
    const float*, float*, int, int, float, unsigned int, unsigned int, void*) {}
extern "C" void gdn_l2_norm_f16(
    const __fp16*, __fp16*, int, int, float, unsigned int, unsigned int, void*) {}

extern "C" void gdn_gated_rmsnorm_f32(
    const float*, const float*, const float*, const float*, float*,
    int, int, int, float, int, int, unsigned int, unsigned int, void*) {}
extern "C" void gdn_gated_rmsnorm_f16(
    const __fp16*, const __fp16*, const float*, const float*, __fp16*,
    int, int, int, float, int, int, unsigned int, unsigned int, void*) {}

extern "C" void gdn_mamba_scatter_f32(
    const float*, float*, const int64_t*, int, int, int, int,
    unsigned int, unsigned int, void*) {}
extern "C" void gdn_mamba_scatter_f16(
    const __fp16*, __fp16*, const int64_t*, int, int, int, int,
    unsigned int, unsigned int, void*) {}
extern "C" void gdn_mamba_scatter_bf16(
    const __bf16*, __bf16*, const int64_t*, int, int, int, int,
    unsigned int, unsigned int, void*) {}
