// Copyright 2025 LancerLab. All Rights Reserved.
// Licensed under the Apache License, Version 2.0.
// SPDX-License-Identifier: Apache-2.0
//
// Generated by Choreo (https://github.com/LancerLab/croqtile.git)
// Source: candle-croq-gdn/kernels/gdn_gating.co
// Do not edit manually — regenerate with: choreo -gs -t topscc -arch=gcu300

#include <tops.h>
#include <tops/half.h>
#include <tops/bfloat.h>
#include <tops/tops_runtime.h>
#include <common/acore_op.h>
#include "choreo_runtime.h"

using namespace choreo;

__co_device__ void f32_to_bf16(void* dst_v, void* src_v, int dim) {
    __bf16* dst = (__bf16*)dst_v;
    float* src = (float*)src_v;
    acore::convert<__bf16, float>(dst, src, dim);
}

__co_device__ void gdn_gating_acore(
    void* a_log_v, void* a_row_v, void* b_row_v, void* dt_bias_v,
    void* g_out_v, void* beta_out_v,
    int dim
) {
    __bf16* a_log = (__bf16*)a_log_v;
    __bf16* a_row = (__bf16*)a_row_v;
    __bf16* b_row = (__bf16*)b_row_v;
    __bf16* dt_bias = (__bf16*)dt_bias_v;
    __bf16* g_out = (__bf16*)g_out_v;
    __bf16* beta_out = (__bf16*)beta_out_v;

    __bf16 tmp_add[256] __attribute__((aligned(256)));
    __bf16 tmp_sp[256] __attribute__((aligned(256)));
    __bf16 tmp_exp[256] __attribute__((aligned(256)));
    __bf16 tmp_neg[256] __attribute__((aligned(256)));

    acore::sigmoid<__bf16, __bf16>(beta_out, b_row, dim);
    acore::add<__bf16, __bf16, __bf16>(tmp_add, a_row, dt_bias, dim);
    acore::softplus<__bf16, __bf16>(tmp_sp, tmp_add, dim);
    acore::exp<__bf16, __bf16>(tmp_exp, a_log, dim);
    acore::neg<__bf16, __bf16>(tmp_neg, tmp_exp, dim);
    acore::mul<__bf16, __bf16, __bf16>(g_out, tmp_neg, tmp_sp, dim);
}

__global__ void __choreo_device_gdn_fused_gating_bf16(float * A_log, choreo::bf16 * A, choreo::bf16 * B, float * Dt_bias, choreo::bf16 * G, choreo::bf16 * Beta, unsigned NUM_HEADS, unsigned TOTAL, unsigned long mr_offset_gdn_fused_gating_bf16_paraby_0_paraby_1_l_a, unsigned long mr_offset_gdn_fused_gating_bf16_paraby_0_paraby_1_l_alog, unsigned long mr_offset_gdn_fused_gating_bf16_paraby_0_paraby_1_l_alog_f32, unsigned long mr_offset_gdn_fused_gating_bf16_paraby_0_paraby_1_l_b, unsigned long mr_offset_gdn_fused_gating_bf16_paraby_0_paraby_1_l_beta, unsigned long mr_offset_gdn_fused_gating_bf16_paraby_0_paraby_1_l_dt, unsigned long mr_offset_gdn_fused_gating_bf16_paraby_0_paraby_1_l_dt_f32, unsigned long mr_offset_gdn_fused_gating_bf16_paraby_0_paraby_1_l_g) {
  choreo::choreo_sdte __choreo_dte_pool__[4];
  for (int __i = 0; __i < 4; ++__i) __choreo_dte_pool__[__i].init();
  { // parallel-by
  __local__ __valigned__ unsigned char anon_0[1572352];
  int sip_id = __tops_tid_x() * 2 + __tops_bid_x();
  int rows_per_sip = ((TOTAL + 23) / 24);
  float* l_alog_f32 = (float*)(anon_0 + mr_offset_gdn_fused_gating_bf16_paraby_0_paraby_1_l_alog_f32);
  float* l_dt_f32 = (float*)(anon_0 + mr_offset_gdn_fused_gating_bf16_paraby_0_paraby_1_l_dt_f32);
  choreo::future la(__choreo_dte_pool__[0], "la", 78, 14, l_alog_f32);
  tops::mdspan __mds0_A_log(tops::Global, (float*)A_log, NUM_HEADS);
  tops::mdspan __mds1_l_alog_f32(tops::Private, (float*)l_alog_f32, NUM_HEADS);
  tops::event la__event__ = tops::memcpy_async(*la.get_ctx(), __mds1_l_alog_f32, __mds0_A_log);
  la.set_event(la__event__);
  choreo::future ld(__choreo_dte_pool__[1], "ld", 79, 14, l_dt_f32);
  tops::mdspan __mds2_Dt_bias(tops::Global, (float*)Dt_bias, NUM_HEADS);
  tops::mdspan __mds3_l_dt_f32(tops::Private, (float*)l_dt_f32, NUM_HEADS);
  tops::event ld__event__ = tops::memcpy_async(*ld.get_ctx(), __mds3_l_dt_f32, __mds2_Dt_bias);
  ld.set_event(ld__event__);
  la.wait();
  ld.wait();
  choreo::bfloat16* l_alog = (choreo::bfloat16*)(anon_0 + mr_offset_gdn_fused_gating_bf16_paraby_0_paraby_1_l_alog);
  choreo::bfloat16* l_dt = (choreo::bfloat16*)(anon_0 + mr_offset_gdn_fused_gating_bf16_paraby_0_paraby_1_l_dt);
  f32_to_bf16((choreo::bf16*)l_alog, (float*)l_alog_f32, NUM_HEADS);
  f32_to_bf16((choreo::bf16*)l_dt, (float*)l_dt_f32, NUM_HEADS);
  choreo::bfloat16* l_a = (choreo::bfloat16*)(anon_0 + mr_offset_gdn_fused_gating_bf16_paraby_0_paraby_1_l_a);
  choreo::bfloat16* l_b = (choreo::bfloat16*)(anon_0 + mr_offset_gdn_fused_gating_bf16_paraby_0_paraby_1_l_b);
  choreo::bfloat16* l_g = (choreo::bfloat16*)(anon_0 + mr_offset_gdn_fused_gating_bf16_paraby_0_paraby_1_l_g);
  choreo::bfloat16* l_beta = (choreo::bfloat16*)(anon_0 + mr_offset_gdn_fused_gating_bf16_paraby_0_paraby_1_l_beta);
  {
    int __iv_row_idx__elem__0 = 0;
    for (__iv_row_idx__elem__0 = 0; __iv_row_idx__elem__0 < rows_per_sip; ++__iv_row_idx__elem__0) {
      int row = (rows_per_sip * sip_id) + __iv_row_idx__elem__0;
      if ((row < TOTAL)) {
        choreo::future la2(__choreo_dte_pool__[2], "la2", 95, 23, l_a);
        tops::mdspan __mds4_A(tops::Global, (choreo::bfloat16*)A, TOTAL, NUM_HEADS);
        tops::mdspan __mds5_l_a(tops::Private, (choreo::bfloat16*)l_a, 1, NUM_HEADS);
        int __slice_offset0__A_2_l_a[] = {(int)(row), 0};
        tops::event la2__event__ = tops::slice_async(*la2.get_ctx(), __mds5_l_a, __mds4_A, __slice_offset0__A_2_l_a);
        la2.set_event(la2__event__);
        choreo::future lb2(__choreo_dte_pool__[3], "lb2", 96, 23, l_b);
        tops::mdspan __mds6_B(tops::Global, (choreo::bfloat16*)B, TOTAL, NUM_HEADS);
        tops::mdspan __mds7_l_b(tops::Private, (choreo::bfloat16*)l_b, 1, NUM_HEADS);
        int __slice_offset1__B_2_l_b[] = {(int)(row), 0};
        tops::event lb2__event__ = tops::slice_async(*lb2.get_ctx(), __mds7_l_b, __mds6_B, __slice_offset1__B_2_l_b);
        lb2.set_event(lb2__event__);
        la2.wait();
        lb2.wait();
        gdn_gating_acore((choreo::bf16*)l_alog, (choreo::bf16*)l_a, (choreo::bf16*)l_b, (choreo::bf16*)l_dt, (choreo::bf16*)l_g, (choreo::bf16*)l_beta, NUM_HEADS);
        choreo::future __choreo_anon_fut__0(__choreo_dte_pool__[0], "", 101, 17);
        tops::mdspan __mds8_l_g(tops::Private, (choreo::bfloat16*)l_g, 1, NUM_HEADS);
        tops::mdspan __mds9_G(tops::Global, (choreo::bfloat16*)G, TOTAL, NUM_HEADS);
        int __deslice_offset0__G_2_l_g[] = {(int)(row), 0};
        tops::deslice(*__choreo_anon_fut__0.get_ctx(), __mds9_G, __mds8_l_g, __deslice_offset0__G_2_l_g);
        choreo::future __choreo_anon_fut__1(__choreo_dte_pool__[0], "", 102, 17);
        tops::mdspan __mds10_l_beta(tops::Private, (choreo::bfloat16*)l_beta, 1, NUM_HEADS);
        tops::mdspan __mds11_Beta(tops::Global, (choreo::bfloat16*)Beta, TOTAL, NUM_HEADS);
        int __deslice_offset1__Beta_2_l_beta[] = {(int)(row), 0};
        tops::deslice(*__choreo_anon_fut__1.get_ctx(), __mds11_Beta, __mds10_l_beta, __deslice_offset1__Beta_2_l_beta);
      }
      __syncthreads();
    }
    __iv_row_idx__elem__0 = 0;
  }
  }
}

void gdn_fused_gating_bf16(const choreo::spanned_view<choreo::f32, 1> & A_log, const choreo::spanned_view<choreo::bf16, 2> & A, const choreo::spanned_view<choreo::bf16, 2> & B, const choreo::spanned_view<choreo::f32, 1> & Dt_bias, const choreo::spanned_view<choreo::bf16, 2> & G, const choreo::spanned_view<choreo::bf16, 2> & Beta, choreo::stream_t _s) {
  auto &NUM_HEADS = A_log.shape()[0];
  auto &TOTAL = A.shape()[0];

  HeapSimulator::Chunks __co__local_chunks;
  __co__local_chunks.push_back({static_cast<size_t>((NUM_HEADS * 2)), {{14,29}}, "_gdn_fused_gating_bf16_paraby_0_paraby_1_l_a"});
  __co__local_chunks.push_back({static_cast<size_t>((NUM_HEADS * 2)), {{10,29}}, "_gdn_fused_gating_bf16_paraby_0_paraby_1_l_alog"});
  __co__local_chunks.push_back({static_cast<size_t>((NUM_HEADS * 4)), {{5,12}}, "_gdn_fused_gating_bf16_paraby_0_paraby_1_l_alog_f32"});
  __co__local_chunks.push_back({static_cast<size_t>((NUM_HEADS * 2)), {{15,29}}, "_gdn_fused_gating_bf16_paraby_0_paraby_1_l_b"});
  __co__local_chunks.push_back({static_cast<size_t>((NUM_HEADS * 2)), {{17,29}}, "_gdn_fused_gating_bf16_paraby_0_paraby_1_l_beta"});
  __co__local_chunks.push_back({static_cast<size_t>((NUM_HEADS * 2)), {{11,29}}, "_gdn_fused_gating_bf16_paraby_0_paraby_1_l_dt"});
  __co__local_chunks.push_back({static_cast<size_t>((NUM_HEADS * 4)), {{6,13}}, "_gdn_fused_gating_bf16_paraby_0_paraby_1_l_dt_f32"});
  __co__local_chunks.push_back({static_cast<size_t>((NUM_HEADS * 2)), {{16,29}}, "_gdn_fused_gating_bf16_paraby_0_paraby_1_l_g"});
  HeapSimulator __co_local_heap_simulator;
  HeapSimulator::Result __co__local_result = __co_local_heap_simulator.Allocate(__co__local_chunks, 512);
  unsigned __co__local_spm_size = __co__local_result.heap_size;
  unsigned long __co__local_chunk_offsets[8];
  size_t __co__local_chunks_idx = 0;
  for (const auto& [buffer_id, offset] : __co__local_result.chunk_offsets)
    __co__local_chunk_offsets[__co__local_chunks_idx++] = offset;
  dim3 __gdn_fused_gating_bf16_gdims0(2, 1, 1);
  dim3 __gdn_fused_gating_bf16_bdims0(12, 1, 1);
  __choreo_device_gdn_fused_gating_bf16<<<__gdn_fused_gating_bf16_gdims0, __gdn_fused_gating_bf16_bdims0, 0, _s>>>(A_log.data(), A.data(), B.data(), Dt_bias.data(), G.data(), Beta.data(), NUM_HEADS, TOTAL, __co__local_chunk_offsets[0], __co__local_chunk_offsets[1], __co__local_chunk_offsets[2], __co__local_chunk_offsets[3], __co__local_chunk_offsets[4], __co__local_chunk_offsets[5], __co__local_chunk_offsets[6], __co__local_chunk_offsets[7]);
}

extern "C" void gdn_fused_gating_bf16_wrapper(
    void* a_log, void* a, void* b, void* dt_bias,
    void* g, void* beta,
    int total, int num_heads, topsStream_t stream) {
  auto alog_sv = croq::make_spanview<1, float>(
      (float*)a_log, {(size_t)num_heads});
  auto a_sv = croq::make_spanview<2, croq::bf16>(
      (croq::bf16*)a, {(size_t)total, (size_t)num_heads});
  auto b_sv = croq::make_spanview<2, croq::bf16>(
      (croq::bf16*)b, {(size_t)total, (size_t)num_heads});
  auto dt_sv = croq::make_spanview<1, float>(
      (float*)dt_bias, {(size_t)num_heads});
  auto g_sv = croq::make_spanview<2, croq::bf16>(
      (croq::bf16*)g, {(size_t)total, (size_t)num_heads});
  auto beta_sv = croq::make_spanview<2, croq::bf16>(
      (croq::bf16*)beta, {(size_t)total, (size_t)num_heads});
  gdn_fused_gating_bf16(alog_sv, a_sv, b_sv, dt_sv, g_sv, beta_sv, stream);
}
