// Copyright 2025 LancerLab. All Rights Reserved.
// Licensed under the Apache License, Version 2.0.
// SPDX-License-Identifier: Apache-2.0
//
// Generated by Choreo (https://github.com/LancerLab/croqtile.git)
// Source: candle-croq-gdn/kernels/gdn_decode_slots_gqa.co
// Do not edit manually — regenerate with: choreo -gs -t topscc -arch=gcu300

#include <tops/tops_runtime.h>
#include <tcle.h>
#include "choreo_runtime.h"

using namespace choreo;

// GDN Decode Slots GQA Kernel (bf16 only, acore-accelerated)
// Processes single-token decode with Grouped-Query-Attention (GQA), fused
// slot-based DMA, q_scale, and exp(g).
//
// Q/K are [BATCH, NKH, KD] — NOT expanded to num_v_heads.
// V/G/Beta/State/Out are [BATCH, NH, VD/F32] as in non-GQA kernel.
// g is LOG-SPACE (exp(g) computed inside kernel).
// q_scale is applied inside the kernel.
//

#include <tops.h>
#include <tops/half.h>
#include <tops/bfloat.h>
#include <tops/tops_runtime.h>
#include <common/acore_op.h>
#include <common/convert.h>

#define VE_F32 (sizeof(__vector float) / sizeof(float))
#define BK_CONST 128
#define BV_CONST 128

__co_device__ void gdn_decode_step_gqa(
    float* state,
    void* k_raw, void* q_raw, void* v_raw,
    float* o_out,
    float* kv_delta_buf,
    float* update_buf,
    float* kq_f32,
    float* v_f32_buf,
    float* g_ptr,
    float* beta_ptr,
    float* q_scale_ptr
) {
    float g_val = expf(g_ptr[0]);
    float beta_val = beta_ptr[0];
    float q_scale = q_scale_ptr[0];
    __bf16* k_f16 = (__bf16*)k_raw;
    __bf16* q_f16 = (__bf16*)q_raw;
    __bf16* v_f16 = (__bf16*)v_raw;

    acore::convert<float, __bf16>(kq_f32, k_f16, BK_CONST);

    acore::matmul<1, acore::MK_KN>(
        kv_delta_buf, kq_f32, state, (float*)nullptr, (int*)nullptr,
        BK_CONST, BV_CONST, 0, 1, 0, 1, 0);

    acore::convert<float, __bf16>(v_f32_buf, v_f16, BV_CONST);

    {
        __vector float vb = (__vector float)beta_val;
        __vector float vg = (__vector float)g_val;
        auto vv = tcle::leaptr<__vector float, 1>(v_f32_buf, sizeof(__vector float));
        auto m_rd = tcle::leaptr<__vector float, 1>(kv_delta_buf, sizeof(__vector float));
        auto d_wr = tcle::leaptr<__vector float, 1>(kv_delta_buf, sizeof(__vector float));
        for (int j = 0; j < BV_CONST; j += VE_F32) {
            d_wr.store<0>((vv.load<0>() - vg * m_rd.load<0>()) * vb);
        }
    }

    acore::outer(update_buf, kq_f32, kv_delta_buf, BK_CONST, BV_CONST);
    acore::add(state, update_buf, state, BK_CONST * BV_CONST, g_val);

    acore::convert<float, __bf16>(kq_f32, q_f16, BK_CONST);
    {
        __vector float vqs = (__vector float)q_scale;
        auto qs_rd = tcle::leaptr<__vector float, 1>(kq_f32, sizeof(__vector float));
        auto qs_wr = tcle::leaptr<__vector float, 1>(kq_f32, sizeof(__vector float));
        for (int j = 0; j < BK_CONST; j += VE_F32) {
            qs_wr.store<0>(qs_rd.load<0>() * vqs);
        }
    }

    acore::matmul<1, acore::MK_KN>(
        o_out, kq_f32, state, (float*)nullptr, (int*)nullptr,
        BK_CONST, BV_CONST, 0, 1, 0, 1, 0);
}

__global__ void __choreo_device_gdn_decode_slots_gqa_bf16(choreo::bf16 * Q, choreo::bf16 * K, choreo::bf16 * V, float * G, float * Beta, float * State, int64_t * Slots, float * QScale, float * Out, int NKH_VAL, int kv_group, unsigned BATCH, unsigned BH, unsigned BKH, unsigned MAX_SLOTS, unsigned NH) {
  choreo::choreo_sdte __choreo_dte_pool__[9];
  for (int __i = 0; __i < 9; ++__i) __choreo_dte_pool__[__i].init();
  {
  __local__ __valigned__ unsigned char anon_0[136192];
  int total_work = BH;
  int items_b0 = ((total_work + 1) / 2);
  int my_items = (__tops_bid_x() == 0 ? items_b0 : total_work - items_b0);
  int my_start = (__tops_bid_x() == 0 ? 0 : items_b0);
  {
    int __iv_wk__elem__0 = 0;
    for (__iv_wk__elem__0 = 0; __iv_wk__elem__0 < ((my_items + 11) / 12); ++__iv_wk__elem__0) {
      if ((__tops_tid_x() + __iv_wk__elem__0 * 12 < my_items)) {
        int bh_idx = my_start + (__iv_wk__elem__0 * 12 + __tops_tid_x());
        int batch_idx = (bh_idx / NH);
        int head_idx = (bh_idx % NH);
        int k_head_idx = (head_idx / kv_group);
        int qk_flat_idx = (NKH_VAL * batch_idx + k_head_idx);
        int64_t* slot_f__buf__ = (int64_t*)(anon_0 + 0);
        choreo::future slot_f(__choreo_dte_pool__[0], "slot_f", 143, 30, slot_f__buf__);
        tops::mdspan __mds0_Slots(tops::Global, (char*)Slots, BATCH, 8);
        tops::mdspan __mds1_slot_f__buf__(tops::Private, (char*)slot_f__buf__, 1, 8);
        int __slice_offset0__Slots_2_slot_f__buf__[] = {(int)(batch_idx), 0};
        tops::event slot_f__event__ = tops::slice_async(*slot_f.get_ctx(), __mds1_slot_f__buf__, __mds0_Slots, __slice_offset0__Slots_2_slot_f__buf__);
        slot_f.set_event(slot_f__event__);
        slot_f.wait();
        int slot = static_cast<int>(*((int64_t*)slot_f.data() + 0));
        float* state_l__buf__ = (float*)(anon_0 + 0);
        choreo::future state_l(__choreo_dte_pool__[1], "state_l", 148, 31, state_l__buf__);
        tops::mdspan __mds2_State(tops::Global, (float*)State, MAX_SLOTS, NH, 128, 128);
        tops::mdspan __mds3_state_l__buf__(tops::Private, (float*)state_l__buf__, 1, 1, 128, 128);
        int __slice_offset1__State_2_state_l__buf__[] = {(int)(slot), (int)(head_idx), 0, 0};
        tops::event state_l__event__ = tops::slice_async(*state_l.get_ctx(), __mds3_state_l__buf__, __mds2_State, __slice_offset1__State_2_state_l__buf__);
        state_l.set_event(state_l__event__);
        choreo::bfloat16* k_l__buf__ = (choreo::bfloat16*)(anon_0 + 133120);
        choreo::future k_l(__choreo_dte_pool__[2], "k_l", 149, 27, k_l__buf__);
        tops::mdspan __mds4_K(tops::Global, (choreo::bfloat16*)K, BKH, 128);
        tops::mdspan __mds5_k_l__buf__(tops::Private, (choreo::bfloat16*)k_l__buf__, 1, 128);
        int __slice_offset2__K_2_k_l__buf__[] = {(int)(qk_flat_idx), 0};
        tops::event k_l__event__ = tops::slice_async(*k_l.get_ctx(), __mds5_k_l__buf__, __mds4_K, __slice_offset2__K_2_k_l__buf__);
        k_l.set_event(k_l__event__);
        choreo::bfloat16* q_l__buf__ = (choreo::bfloat16*)(anon_0 + 133632);
        choreo::future q_l(__choreo_dte_pool__[3], "q_l", 150, 27, q_l__buf__);
        tops::mdspan __mds6_Q(tops::Global, (choreo::bfloat16*)Q, BKH, 128);
        tops::mdspan __mds7_q_l__buf__(tops::Private, (choreo::bfloat16*)q_l__buf__, 1, 128);
        int __slice_offset3__Q_2_q_l__buf__[] = {(int)(qk_flat_idx), 0};
        tops::event q_l__event__ = tops::slice_async(*q_l.get_ctx(), __mds7_q_l__buf__, __mds6_Q, __slice_offset3__Q_2_q_l__buf__);
        q_l.set_event(q_l__event__);
        choreo::bfloat16* v_l__buf__ = (choreo::bfloat16*)(anon_0 + 134144);
        choreo::future v_l(__choreo_dte_pool__[4], "v_l", 151, 27, v_l__buf__);
        tops::mdspan __mds8_V(tops::Global, (choreo::bfloat16*)V, BH, 128);
        tops::mdspan __mds9_v_l__buf__(tops::Private, (choreo::bfloat16*)v_l__buf__, 1, 128);
        int __slice_offset4__V_2_v_l__buf__[] = {(int)(bh_idx), 0};
        tops::event v_l__event__ = tops::slice_async(*v_l.get_ctx(), __mds9_v_l__buf__, __mds8_V, __slice_offset4__V_2_v_l__buf__);
        v_l.set_event(v_l__event__);
        float* g_l__buf__ = (float*)(anon_0 + 135168);
        choreo::future g_l(__choreo_dte_pool__[5], "g_l", 152, 27, g_l__buf__);
        tops::mdspan __mds10_G(tops::Global, (float*)G, BH);
        tops::mdspan __mds11_g_l__buf__(tops::Private, (float*)g_l__buf__, 1);
        int __slice_offset5__G_2_g_l__buf__[] = {(int)(bh_idx)};
        tops::event g_l__event__ = tops::slice_async(*g_l.get_ctx(), __mds11_g_l__buf__, __mds10_G, __slice_offset5__G_2_g_l__buf__);
        g_l.set_event(g_l__event__);
        float* beta_l__buf__ = (float*)(anon_0 + 134656);
        choreo::future beta_l(__choreo_dte_pool__[6], "beta_l", 153, 30, beta_l__buf__);
        tops::mdspan __mds12_Beta(tops::Global, (float*)Beta, BH);
        tops::mdspan __mds13_beta_l__buf__(tops::Private, (float*)beta_l__buf__, 1);
        int __slice_offset6__Beta_2_beta_l__buf__[] = {(int)(bh_idx)};
        tops::event beta_l__event__ = tops::slice_async(*beta_l.get_ctx(), __mds13_beta_l__buf__, __mds12_Beta, __slice_offset6__Beta_2_beta_l__buf__);
        beta_l.set_event(beta_l__event__);
        float* kv_delta_l = (float*)(anon_0 + 131584);
        float* update_l = (float*)(anon_0 + 65536);
        float* kq_f32_l = (float*)(anon_0 + 131072);
        float* v_f32_l = (float*)(anon_0 + 132608);
        float* out_l = (float*)(anon_0 + 132096);
        float* qs_f__buf__ = (float*)(anon_0 + 135680);
        choreo::future qs_f(__choreo_dte_pool__[7], "qs_f", 161, 28, qs_f__buf__);
        tops::mdspan __mds14_QScale(tops::Global, (float*)QScale, 1);
        tops::mdspan __mds15_qs_f__buf__(tops::Private, (float*)qs_f__buf__, 1);
        int __slice_offset7__QScale_2_qs_f__buf__[] = {0};
        tops::event qs_f__event__ = tops::slice_async(*qs_f.get_ctx(), __mds15_qs_f__buf__, __mds14_QScale, __slice_offset7__QScale_2_qs_f__buf__);
        qs_f.set_event(qs_f__event__);
        state_l.wait();
        k_l.wait();
        q_l.wait();
        v_l.wait();
        g_l.wait();
        beta_l.wait();
        qs_f.wait();
        gdn_decode_step_gqa((float*)state_l.data(), (choreo::bf16*)k_l.data(), (choreo::bf16*)q_l.data(), (choreo::bf16*)v_l.data(), (float*)out_l, (float*)kv_delta_l, (float*)update_l, (float*)kq_f32_l, (float*)v_f32_l, (float*)g_l.data(), (float*)beta_l.data(), (float*)qs_f.data());
        choreo::future __choreo_anon_fut__0(__choreo_dte_pool__[8], "", 172, 21);
        tops::mdspan __mds16_out_l(tops::Private, (float*)out_l, 1, 128);
        tops::mdspan __mds17_Out(tops::Global, (float*)Out, BH, 128);
        int __deslice_offset0__Out_2_out_l[] = {(int)(bh_idx), 0};
        tops::deslice(*__choreo_anon_fut__0.get_ctx(), __mds17_Out, __mds16_out_l, __deslice_offset0__Out_2_out_l);
        choreo::future __choreo_anon_fut__1(__choreo_dte_pool__[8], "", 173, 21);
        tops::mdspan __mds18_state_l(tops::Private, (float*)state_l.data(), 1, 1, 128, 128);
        tops::mdspan __mds19_State(tops::Global, (float*)State, MAX_SLOTS, NH, 128, 128);
        int __deslice_offset1__State_2_state_l[] = {(int)(slot), (int)(head_idx), 0, 0};
        tops::deslice(*__choreo_anon_fut__1.get_ctx(), __mds19_State, __mds18_state_l, __deslice_offset1__State_2_state_l);
      }
      __syncthreads();
    }
    __iv_wk__elem__0 = 0;
  }
  }
}

void gdn_decode_slots_gqa_bf16(const choreo::spanned_view<choreo::bf16, 2> & Q, const choreo::spanned_view<choreo::bf16, 2> & K, const choreo::spanned_view<choreo::bf16, 2> & V, const choreo::spanned_view<choreo::f32, 1> & G, const choreo::spanned_view<choreo::f32, 1> & Beta, const choreo::spanned_view<choreo::f32, 4> & State, const choreo::spanned_view<choreo::s64, 1> & Slots, const choreo::spanned_view<choreo::f32, 1> & QScale, const choreo::spanned_view<choreo::f32, 2> & Out, choreo::stream_t _s) {
  auto &BATCH = Slots.shape()[0];
  auto &BH = V.shape()[0];
  auto &BKH = Q.shape()[0];
  auto &MAX_SLOTS = State.shape()[0];
  auto &NH = State.shape()[1];
  int NKH_VAL = (int)(BKH / BATCH);
  int kv_group = (int)(NH / NKH_VAL);
  dim3 __gdn_decode_slots_gqa_bf16_gdims0(2, 1, 1);
  dim3 __gdn_decode_slots_gqa_bf16_bdims0(12, 1, 1);
  __choreo_device_gdn_decode_slots_gqa_bf16<<<__gdn_decode_slots_gqa_bf16_gdims0, __gdn_decode_slots_gqa_bf16_bdims0, 0, _s>>>(Q.data(), K.data(), V.data(), G.data(), Beta.data(), State.data(), Slots.data(), QScale.data(), Out.data(), NKH_VAL, kv_group, BATCH, BH, BKH, MAX_SLOTS, NH);
}

// === Wrapper: raw pointers → spanned_view ===
extern "C" void gdn_decode_slots_gqa_bf16(
    void* q, void* k, void* v,
    float* g, float* beta,
    float* state, int64_t* slots, float* qscale, float* out,
    int batch, int num_v_heads, int num_k_heads, int k_dim, int v_dim,
    int max_slots, int num_blocks, int dim_blocks, topsStream_t stream) {
  int bkh = batch * num_k_heads;
  int bh = batch * num_v_heads;
  auto q_sv = croq::make_spanview<2, croq::bf16>(
      (croq::bf16*)q, {(size_t)bkh, (size_t)k_dim});
  auto k_sv = croq::make_spanview<2, croq::bf16>(
      (croq::bf16*)k, {(size_t)bkh, (size_t)k_dim});
  auto v_sv = croq::make_spanview<2, croq::bf16>(
      (croq::bf16*)v, {(size_t)bh, (size_t)v_dim});
  auto g_sv = croq::make_spanview<1, float>(g, {(size_t)bh});
  auto beta_sv = croq::make_spanview<1, float>(beta, {(size_t)bh});
  auto state_sv = croq::make_spanview<4, float>(
      state, {(size_t)max_slots, (size_t)num_v_heads, (size_t)k_dim, (size_t)v_dim});
  auto slots_sv = croq::make_spanview<1, int64_t>(
      slots, {(size_t)batch});
  auto qscale_sv = croq::make_spanview<1, float>(qscale, {1UL});
  auto out_sv = croq::make_spanview<2, float>(
      out, {(size_t)bh, (size_t)v_dim});
  (void)num_blocks; (void)dim_blocks;
  gdn_decode_slots_gqa_bf16(q_sv, k_sv, v_sv, g_sv, beta_sv, state_sv, slots_sv, qscale_sv, out_sv, stream);
}
