// Copyright 2025 LancerLab. All Rights Reserved.
// Licensed under the Apache License, Version 2.0.
// SPDX-License-Identifier: Apache-2.0
//
// Generated by Choreo (https://github.com/LancerLab/croqtile.git)
// Source: candle-croq-gdn/kernels/gdn_l2norm.co
// Do not edit manually — regenerate with: choreo -gs -t topscc -arch=gcu300

#include <tops.h>
#include <tops/half.h>
#include <tops/bfloat.h>
#include <tops/tops_runtime.h>
#include <tops/topscc_types.h>
#include <tcle.h>
#include "choreo_runtime.h"

using namespace choreo;

using vf = __vector4 float;
using vb = __vector2 __bf16;

__co_device__ void l2norm_vec_inplace(void* buf_v, float eps) {
    __bf16* buf = (__bf16*)buf_v;

    vb raw = *(vb*)buf;
    vf xf = tcle::cvt<vf>(raw);

    vf sq = xf * xf;
    float sum_sq = tops::vreduce_sum<float>(sq);
    float inv_norm = tcle::rsqrt(sum_sq + eps);
    vf result = xf * (vf)(inv_norm);

    *(vb*)buf = tcle::cvt<vb>(result);
}

__global__ void __choreo_device_gdn_l2_norm_bf16(choreo::bf16 * Input, choreo::bf16 * Output, unsigned DIM, unsigned ROWS, unsigned long mr_offset_gdn_l2_norm_bf16_paraby_0_paraby_1_l_in) {
  choreo::choreo_sdte __choreo_dte_pool__[1];
  for (int __i = 0; __i < 1; ++__i) __choreo_dte_pool__[__i].init();
  { // parallel-by
  __local__ __valigned__ unsigned char anon_0[1572352];
  int sip_id = __tops_tid_x() * 2 + __tops_bid_x();
  int rows_per_sip = ((ROWS + 23) / 24);
  choreo::bfloat16* l_in = (choreo::bfloat16*)(anon_0 + mr_offset_gdn_l2_norm_bf16_paraby_0_paraby_1_l_in);
  {
    int __iv_row_idx__elem__0 = 0;
    for (__iv_row_idx__elem__0 = 0; __iv_row_idx__elem__0 < rows_per_sip; ++__iv_row_idx__elem__0) {
      int row = (rows_per_sip * sip_id) + __iv_row_idx__elem__0;
      if ((row < ROWS)) {
        choreo::future l(__choreo_dte_pool__[0], "l", 58, 21, l_in);
        tops::mdspan __mds0_Input(tops::Global, (choreo::bfloat16*)Input, ROWS, DIM);
        tops::mdspan __mds1_l_in(tops::Private, (choreo::bfloat16*)l_in, 1, DIM);
        int __slice_offset0__Input_2_l_in[] = {(int)(row), 0};
        tops::event l__event__ = tops::slice_async(*l.get_ctx(), __mds1_l_in, __mds0_Input, __slice_offset0__Input_2_l_in);
        l.set_event(l__event__);
        l.wait();
        l2norm_vec_inplace((choreo::bf16*)l_in, 0.000001f);
        choreo::future __choreo_anon_fut__0(__choreo_dte_pool__[0], "", 63, 17);
        tops::mdspan __mds2_l_in(tops::Private, (choreo::bfloat16*)l_in, 1, DIM);
        tops::mdspan __mds3_Output(tops::Global, (choreo::bfloat16*)Output, ROWS, DIM);
        int __deslice_offset0__Output_2_l_in[] = {(int)(row), 0};
        tops::deslice(*__choreo_anon_fut__0.get_ctx(), __mds3_Output, __mds2_l_in, __deslice_offset0__Output_2_l_in);
      }
      __syncthreads();
    }
    __iv_row_idx__elem__0 = 0;
  }
  }
}

void gdn_l2_norm_bf16(const choreo::spanned_view<choreo::bf16, 2> & Input, const choreo::spanned_view<choreo::bf16, 2> & Output, choreo::stream_t _s) {
  auto &DIM = Input.shape()[1];
  auto &ROWS = Input.shape()[0];
  choreo::runtime_check(Input.shape()[1] == Output.shape()[1], "The shapes of the 1st parameter (dim: 1) and the 2nd parameter (dim: 1) are inconsistent.");
  choreo::runtime_check(Input.shape()[0] == Output.shape()[0], "The shapes of the 1st parameter (dim: 0) and the 2nd parameter (dim: 0) are inconsistent.");

  choreo::runtime_check((static_cast<long long>(DIM) * 2LL < 4294967296LL), "The size of data transferred by DMA cannot exceed 2^32., 58.21");
  choreo::runtime_check((static_cast<long long>(DIM) < 16777216LL), "On GCU300, must satisfy: the 2nd dim ::gdn_l2_norm_bf16::DIM < 16777216., 58.36");
  choreo::runtime_check((static_cast<long long>(DIM) < 16777216LL), "On GCU300, must satisfy: the 2nd dim ::gdn_l2_norm_bf16::DIM < 16777216., 58.72");
  choreo::runtime_check((static_cast<long long>(DIM) * 2LL < 4294967296LL), "The size of data transferred by DMA cannot exceed 2^32., 63.17");
  choreo::runtime_check((static_cast<long long>(DIM) < 16777216LL), "On GCU300, must satisfy: the 2nd dim ::gdn_l2_norm_bf16::DIM < 16777216., 63.26");
  choreo::runtime_check((static_cast<long long>(DIM) < 16777216LL), "On GCU300, must satisfy: the 2nd dim ::gdn_l2_norm_bf16::DIM < 16777216., 63.34");
  HeapSimulator::Chunks __co__local_chunks;
  __co__local_chunks.push_back({static_cast<size_t>((DIM * 2)), {{5,15}}, "_gdn_l2_norm_bf16_paraby_0_paraby_1_l_in"});
  HeapSimulator __co_local_heap_simulator;
  HeapSimulator::Result __co__local_result = __co_local_heap_simulator.Allocate(__co__local_chunks, 512);
  unsigned __co__local_spm_size = __co__local_result.heap_size;
  choreo::runtime_check(__co__local_spm_size <= (size_t)1572352, "In the memory reuse of dynamic shapes, the size of the initial local spm should not exceed the memory usage limit 1572352 bytes.");
  unsigned long __co__local_chunk_offsets[1];
  size_t __co__local_chunks_idx = 0;
  for (const auto& [buffer_id, offset] : __co__local_result.chunk_offsets)
    __co__local_chunk_offsets[__co__local_chunks_idx++] = offset;
  dim3 __gdn_l2_norm_bf16_gdims0(2, 1, 1);
  dim3 __gdn_l2_norm_bf16_bdims0(12, 1, 1);
  __choreo_device_gdn_l2_norm_bf16<<<__gdn_l2_norm_bf16_gdims0, __gdn_l2_norm_bf16_bdims0, 0, _s>>>(Input.data(), Output.data(), DIM, ROWS, __co__local_chunk_offsets[0]);
}

extern "C" void gdn_l2_norm_bf16_wrapper(
    void* input, void* output,
    int rows, int dim, topsStream_t stream) {
  auto in_sv = croq::make_spanview<2, croq::bf16>(
      (croq::bf16*)input, {(size_t)rows, (size_t)dim});
  auto out_sv = croq::make_spanview<2, croq::bf16>(
      (croq::bf16*)output, {(size_t)rows, (size_t)dim});
  gdn_l2_norm_bf16(in_sv, out_sv, stream);
}
