// Copyright 2025 LancerLab. All Rights Reserved.
// Licensed under the Apache License, Version 2.0.
// SPDX-License-Identifier: Apache-2.0
//
// Generated by Choreo (https://github.com/LancerLab/croqtile.git)
// Source: candle-croq-gdn/kernels/gdn_recurrence_varlen.co
// Do not edit manually — regenerate with: choreo -gs -t topscc -arch=gcu300

#include <tops/tops_runtime.h>
#include <tcle.h>
#include "choreo_runtime.h"

using namespace choreo;

// iter001: Replace ALL scalar loops with acore ops.
// Based on iter000 (scalar baseline, 0.000660 TFLOPS).
// Changes:
//   - decay: scalar loop → acore::mul
//   - gemv (S^T@k): scalar → acore::convert bf16→f32 + acore::matmul<1, MK_KN>
//   - outer product: scalar → acore::outer + acore::add(alpha) for fused decay
//   - readout (S^T@q): scalar → acore::matmul<1, MK_KN>
//   - output: acore::convert f32→bf16
//   - All acore output buffers are DMA-allocated (local f32[...])

#include <tops.h>
#include <tops/half.h>
#include <tops/bfloat.h>
#include <tops/tops_runtime.h>
#include <common/acore_op.h>
#include <common/convert.h>

#define BK_CONST 128
#define BV_CONST 128
#define VE_F32 (sizeof(__vector float) / sizeof(float))

using vf = __vector4 float;
using vb = __vector2 __bf16;

__co_device__ void l2_norm_bf16_128_to_f32(
    float* out_f32_v, void* in_bf16_v, float eps
) {
    float* out_f32 = (float*)out_f32_v;
    __bf16* in_bf16 = (__bf16*)in_bf16_v;
    vb x_raw = *(vb*)in_bf16;
    vf xf = tcle::cvt<vf>(x_raw);
    vf sq = xf * xf;
    float sum_sq = tops::vreduce_sum<float>(sq);
    vf normalized = xf * (vf)(tcle::rsqrt(sum_sq + eps));
    *(vf*)out_f32 = normalized;
}

__co_device__ void gdn_recurrence_step_varlen_acore(
    float* state,
    void* q_v, void* k_v, void* v_v,
    float g_val, float beta_val,
    float* o_out,
    void* o_bf16_out,
    float* kq_f32,
    float* kv_delta_buf,
    float* update_buf,
    float* v_f32_buf,
    float q_scale,
    bool normalize_qk
) {
    __bf16* q_f16 = (__bf16*)q_v;
    __bf16* k_f16 = (__bf16*)k_v;
    __bf16* v_f16 = (__bf16*)v_v;

    // Step 1+2 combined: normalize/convert k, then kv_mem = S^T @ k.
    if (normalize_qk) {
        l2_norm_bf16_128_to_f32(kq_f32, k_f16, 1e-6f);
    } else {
        acore::convert<float, __bf16>(kq_f32, k_f16, BK_CONST);
    }
    acore::matmul<1, acore::MK_KN>(
        kv_delta_buf, kq_f32, state, (float*)nullptr, (int*)nullptr,
        BK_CONST, BV_CONST, 0, 1, 0, 1, 0);

    // Step 3: delta = (v - g*kv_mem) * beta (vectorized, in-place into kv_delta_buf)
    acore::convert<float, __bf16>(v_f32_buf, v_f16, BV_CONST);
    {
        __vector float vb = (__vector float)beta_val;
        __vector float vg = (__vector float)g_val;
        auto v_rd = tcle::leaptr<__vector float, 1>(v_f32_buf, sizeof(__vector float));
        auto m_rd = tcle::leaptr<__vector float, 1>(kv_delta_buf, sizeof(__vector float));
        auto d_wr = tcle::leaptr<__vector float, 1>(kv_delta_buf, sizeof(__vector float));
        for (int j = 0; j < BV_CONST; j += VE_F32) {
            d_wr.store<0>((v_rd.load<0>() - vg * m_rd.load<0>()) * vb);
        }
    }

    // Step 4: S = g*S + outer(k, delta) via acore::outer + fused add
    acore::outer(update_buf, kq_f32, kv_delta_buf, BK_CONST, BV_CONST);
    acore::add(state, update_buf, state, BK_CONST * BV_CONST, g_val);

    // Step 5: readout o = S^T @ q. GQA prefill also normalizes and scales q
    // here, avoiding a separate full-token tensor operation.
    if (normalize_qk) {
        l2_norm_bf16_128_to_f32(kq_f32, q_f16, 1e-6f);
    } else {
        acore::convert<float, __bf16>(kq_f32, q_f16, BK_CONST);
    }
    if (q_scale != 1.0f) {
        auto q_rd = tcle::leaptr<__vector float, 1>(kq_f32, sizeof(__vector float));
        auto q_wr = tcle::leaptr<__vector float, 1>(kq_f32, sizeof(__vector float));
        __vector float scale = (__vector float)q_scale;
        for (int j = 0; j < BK_CONST; j += VE_F32) {
            q_wr.store<0>(q_rd.load<0>() * scale);
        }
    }
    acore::matmul<1, acore::MK_KN>(
        o_out, kq_f32, state, (float*)nullptr, (int*)nullptr,
        BK_CONST, BV_CONST, 0, 1, 0, 1, 0);

    // Convert output to bf16
    acore::convert<__bf16, float>((__bf16*)o_bf16_out, o_out, BV_CONST);
}

#define KD 128
#define VD 128
__global__ void __choreo_device_gdn_recurrence_varlen_bf16(choreo::bf16 * Q, choreo::bf16 * K, choreo::bf16 * V, choreo::bf16 * G, choreo::bf16 * Beta, float * State, int64_t * Slots, choreo::bf16 * Out, unsigned int * CuSeqlens, unsigned BATCH, unsigned BATCH_P1, unsigned MAX_SLOTS, unsigned NHQ, unsigned NHV, unsigned TOTAL_TOKENS, float QScale, unsigned NORMALIZE_QK) {
  choreo::choreo_sdte __choreo_dte_pool__[9];
  for (int __i = 0; __i < 9; ++__i) __choreo_dte_pool__[__i].init();
  { // parallel-by: 96.24
  __local__ __valigned__ unsigned char anon_1[136192];
  int sip_id = __tops_tid_x() * 2 + __tops_bid_x();
  int total_work = (BATCH * NHV);
  int work_per_sip = ((total_work + 23) / 24);
  // with-in: 102.9
  {
    int __iv_wi__elem__0 = 0;
    // foreach: 102.9
    for (__iv_wi__elem__0 = 0; __iv_wi__elem__0 < work_per_sip; ++__iv_wi__elem__0) {
      int work_id = (sip_id * work_per_sip) + __iv_wi__elem__0;
      // inthreads: 104.13
      if ((work_id < total_work)) {
        int seq_idx = (work_id / NHV);
        int head_idx = (work_id % NHV);
        int q_head_idx = head_idx / (NHV / NHQ);
        int64_t* slot_f__buf__ = (int64_t*)(anon_1 + 0);
        choreo::future slot_f(__choreo_dte_pool__[0], "slot_f", 108, 26, slot_f__buf__);
        tops::mdspan __mds0_Slots(tops::Global, (char*)Slots, BATCH, 8);
        tops::mdspan __mds1_slot_f__buf__(tops::Private, (char*)slot_f__buf__, 1, 8);
        int __slice_offset0__Slots_2_slot_f__buf__[] = {(int)(seq_idx), 0};
        tops::event slot_f__event__ = tops::slice_async(*slot_f.get_ctx(), __mds1_slot_f__buf__, __mds0_Slots, __slice_offset0__Slots_2_slot_f__buf__);
        slot_f.set_event(slot_f__event__);
        unsigned int* cu_start_f__buf__ = (unsigned int*)(anon_1 + 1024);
        choreo::future cu_start_f(__choreo_dte_pool__[1], "cu_start_f", 109, 30, cu_start_f__buf__);
        tops::mdspan __mds2_CuSeqlens(tops::Global, (unsigned int*)CuSeqlens, BATCH_P1);
        tops::mdspan __mds3_cu_start_f__buf__(tops::Private, (unsigned int*)cu_start_f__buf__, 1);
        int __slice_offset1__CuSeqlens_2_cu_start_f__buf__[] = {(int)(seq_idx)};
        tops::event cu_start_f__event__ = tops::slice_async(*cu_start_f.get_ctx(), __mds3_cu_start_f__buf__, __mds2_CuSeqlens, __slice_offset1__CuSeqlens_2_cu_start_f__buf__);
        cu_start_f.set_event(cu_start_f__event__);
        auto anon_0 = (seq_idx + 1);
        unsigned int* cu_end_f__buf__ = (unsigned int*)(anon_1 + 512);
        choreo::future cu_end_f(__choreo_dte_pool__[2], "cu_end_f", 110, 28, cu_end_f__buf__);
        tops::mdspan __mds4_CuSeqlens(tops::Global, (unsigned int*)CuSeqlens, BATCH_P1);
        tops::mdspan __mds5_cu_end_f__buf__(tops::Private, (unsigned int*)cu_end_f__buf__, 1);
        int __slice_offset2__CuSeqlens_2_cu_end_f__buf__[] = {(int)(anon_0)};
        tops::event cu_end_f__event__ = tops::slice_async(*cu_end_f.get_ctx(), __mds5_cu_end_f__buf__, __mds4_CuSeqlens, __slice_offset2__CuSeqlens_2_cu_end_f__buf__);
        cu_end_f.set_event(cu_end_f__event__);
        slot_f.wait();
        cu_start_f.wait();
        cu_end_f.wait();
        int slot = static_cast<int>(*((int64_t*)slot_f.data() + 0));
        int start = static_cast<int>(*((unsigned int*)cu_start_f.data() + 0));
        int end_t = static_cast<int>(*((unsigned int*)cu_end_f.data() + 0));
        int seq_len = (end_t - start);
        float* state_l__buf__ = (float*)(anon_1 + 0);
        choreo::future state_l(__choreo_dte_pool__[3], "state_l", 118, 27, state_l__buf__);
        tops::mdspan __mds6_State(tops::Global, (float*)State, MAX_SLOTS, NHV, 128, 128);
        tops::mdspan __mds7_state_l__buf__(tops::Private, (float*)state_l__buf__, 1, 1, 128, 128);
        int __slice_offset3__State_2_state_l__buf__[] = {(int)(slot), (int)(head_idx), 0, 0};
        tops::event state_l__event__ = tops::slice_async(*state_l.get_ctx(), __mds7_state_l__buf__, __mds6_State, __slice_offset3__State_2_state_l__buf__);
        state_l.set_event(state_l__event__);
        float* out_l = (float*)(anon_1 + 132096);
        float* kq_f32_l = (float*)(anon_1 + 131072);
        choreo::bfloat16* out_bf16_l = (choreo::bfloat16*)(anon_1 + 133120);
        float* kv_delta_l = (float*)(anon_1 + 131584);
        float* update_l = (float*)(anon_1 + 65536);
        float* v_f32_l = (float*)(anon_1 + 132608);
        state_l.wait();
        // with-in: 130.17
        {
          int __iv_t__elem__0 = 0;
          // foreach: 130.17
          for (__iv_t__elem__0 = 0; __iv_t__elem__0 < seq_len; ++__iv_t__elem__0) {
            int token_idx = start + __iv_t__elem__0;
            choreo::bfloat16* q_l__buf__ = (choreo::bfloat16*)(anon_1 + 134144);
            choreo::future q_l(__choreo_dte_pool__[4], "q_l", 133, 27, q_l__buf__);
            tops::mdspan __mds8_Q(tops::Global, (choreo::bfloat16*)Q, TOTAL_TOKENS, NHQ, 128);
            tops::mdspan __mds9_q_l__buf__(tops::Private, (choreo::bfloat16*)q_l__buf__, 1, 1, 128);
            int __slice_offset4__Q_2_q_l__buf__[] = {(int)(token_idx), (int)(q_head_idx), 0};
            tops::event q_l__event__ = tops::slice_async(*q_l.get_ctx(), __mds9_q_l__buf__, __mds8_Q, __slice_offset4__Q_2_q_l__buf__);
            q_l.set_event(q_l__event__);
            choreo::bfloat16* k_l__buf__ = (choreo::bfloat16*)(anon_1 + 133632);
            choreo::future k_l(__choreo_dte_pool__[5], "k_l", 134, 27, k_l__buf__);
            tops::mdspan __mds10_K(tops::Global, (choreo::bfloat16*)K, TOTAL_TOKENS, NHQ, 128);
            tops::mdspan __mds11_k_l__buf__(tops::Private, (choreo::bfloat16*)k_l__buf__, 1, 1, 128);
            int __slice_offset5__K_2_k_l__buf__[] = {(int)(token_idx), (int)(q_head_idx), 0};
            tops::event k_l__event__ = tops::slice_async(*k_l.get_ctx(), __mds11_k_l__buf__, __mds10_K, __slice_offset5__K_2_k_l__buf__);
            k_l.set_event(k_l__event__);
            choreo::bfloat16* v_l__buf__ = (choreo::bfloat16*)(anon_1 + 134656);
            choreo::future v_l(__choreo_dte_pool__[6], "v_l", 135, 27, v_l__buf__);
            tops::mdspan __mds12_V(tops::Global, (choreo::bfloat16*)V, TOTAL_TOKENS, NHV, 128);
            tops::mdspan __mds13_v_l__buf__(tops::Private, (choreo::bfloat16*)v_l__buf__, 1, 1, 128);
            int __slice_offset6__V_2_v_l__buf__[] = {(int)(token_idx), (int)(head_idx), 0};
            tops::event v_l__event__ = tops::slice_async(*v_l.get_ctx(), __mds13_v_l__buf__, __mds12_V, __slice_offset6__V_2_v_l__buf__);
            v_l.set_event(v_l__event__);
            choreo::bfloat16* g_f__buf__ = (choreo::bfloat16*)(anon_1 + 135680);
            choreo::future g_f(__choreo_dte_pool__[7], "g_f", 136, 27, g_f__buf__);
            tops::mdspan __mds14_G(tops::Global, (choreo::bfloat16*)G, TOTAL_TOKENS, NHV);
            tops::mdspan __mds15_g_f__buf__(tops::Private, (choreo::bfloat16*)g_f__buf__, 1, 1);
            int __slice_offset7__G_2_g_f__buf__[] = {(int)(token_idx), (int)(head_idx)};
            tops::event g_f__event__ = tops::slice_async(*g_f.get_ctx(), __mds15_g_f__buf__, __mds14_G, __slice_offset7__G_2_g_f__buf__);
            g_f.set_event(g_f__event__);
            choreo::bfloat16* beta_f__buf__ = (choreo::bfloat16*)(anon_1 + 135168);
            choreo::future beta_f(__choreo_dte_pool__[8], "beta_f", 137, 30, beta_f__buf__);
            tops::mdspan __mds16_Beta(tops::Global, (choreo::bfloat16*)Beta, TOTAL_TOKENS, NHV);
            tops::mdspan __mds17_beta_f__buf__(tops::Private, (choreo::bfloat16*)beta_f__buf__, 1, 1);
            int __slice_offset8__Beta_2_beta_f__buf__[] = {(int)(token_idx), (int)(head_idx)};
            tops::event beta_f__event__ = tops::slice_async(*beta_f.get_ctx(), __mds17_beta_f__buf__, __mds16_Beta, __slice_offset8__Beta_2_beta_f__buf__);
            beta_f.set_event(beta_f__event__);
            q_l.wait();
            k_l.wait();
            v_l.wait();
            g_f.wait();
            beta_f.wait();
            float g_val = bf16_to_f32(*((choreo::bfloat16*)g_f.data() + 0));
            float beta_val = bf16_to_f32(*((choreo::bfloat16*)beta_f.data() + 0));
            gdn_recurrence_step_varlen_acore((float*)state_l.data(), (choreo::bf16*)q_l.data(), (choreo::bf16*)k_l.data(), (choreo::bf16*)v_l.data(), g_val, beta_val, (float*)out_l, (choreo::bf16*)out_bf16_l, (float*)kq_f32_l, (float*)kv_delta_l, (float*)update_l, (float*)v_f32_l, QScale, NORMALIZE_QK != 0);
            choreo::future __choreo_anon_fut__0(__choreo_dte_pool__[0], "", 152, 21);
            tops::mdspan __mds18_out_bf16_l(tops::Private, (choreo::bfloat16*)out_bf16_l, 1, 1, 128);
            tops::mdspan __mds19_Out(tops::Global, (choreo::bfloat16*)Out, TOTAL_TOKENS, NHV, 128);
            int __deslice_offset0__Out_2_out_bf16_l[] = {(int)(token_idx), (int)(head_idx), 0};
            tops::deslice(*__choreo_anon_fut__0.get_ctx(), __mds19_Out, __mds18_out_bf16_l, __deslice_offset0__Out_2_out_bf16_l);
          } // t__elem__0
          __iv_t__elem__0 = 0;
        }
        choreo::future __choreo_anon_fut__1(__choreo_dte_pool__[0], "", 155, 17);
        tops::mdspan __mds20_state_l(tops::Private, (float*)state_l.data(), 1, 1, 128, 128);
        tops::mdspan __mds21_State(tops::Global, (float*)State, MAX_SLOTS, NHV, 128, 128);
        int __deslice_offset1__State_2_state_l[] = {(int)(slot), (int)(head_idx), 0, 0};
        tops::deslice(*__choreo_anon_fut__1.get_ctx(), __mds21_State, __mds20_state_l, __deslice_offset1__State_2_state_l);
      }
      __syncthreads(); // end inthreads
    } // wi__elem__0
    __iv_wi__elem__0 = 0;
  }
  } // end parallel-by
}

void gdn_recurrence_varlen_bf16(const choreo::spanned_view<choreo::bf16, 3> & Q, const choreo::spanned_view<choreo::bf16, 3> & K, const choreo::spanned_view<choreo::bf16, 3> & V, const choreo::spanned_view<choreo::bf16, 2> & G, const choreo::spanned_view<choreo::bf16, 2> & Beta, const choreo::spanned_view<choreo::f32, 4> & State, const choreo::spanned_view<choreo::s64, 1> & Slots, const choreo::spanned_view<choreo::bf16, 3> & Out, const choreo::spanned_view<choreo::u32, 1> & CuSeqlens, float QScale, unsigned NORMALIZE_QK, choreo::stream_t _s) {
  auto &BATCH = Slots.shape()[0];
  auto &BATCH_P1 = CuSeqlens.shape()[0];
  auto &MAX_SLOTS = State.shape()[0];
  auto &NHQ = Q.shape()[1];
  auto &NHV = V.shape()[1];
  auto &TOTAL_TOKENS = Q.shape()[0];

  dim3 __gdn_recurrence_varlen_bf16_gdims0(2, 1, 1);
  dim3 __gdn_recurrence_varlen_bf16_bdims0(12, 1, 1);
  __choreo_device_gdn_recurrence_varlen_bf16<<<__gdn_recurrence_varlen_bf16_gdims0, __gdn_recurrence_varlen_bf16_bdims0, 0, _s>>>(Q.data(), K.data(), V.data(), G.data(), Beta.data(), State.data(), Slots.data(), Out.data(), CuSeqlens.data(), BATCH, BATCH_P1, MAX_SLOTS, NHQ, NHV, TOTAL_TOKENS, QScale, NORMALIZE_QK);
}
// CPU reference for correctness verification (varlen layout)

// === Wrapper: raw pointers → spanned_view ===
extern "C" void gdn_recurrence_varlen_bf16_wrapper(
    void* q, void* k, void* v,
    void* g, void* beta,
    float* state, int64_t* slots, void* out, uint32_t* cu_seqlens,
    int total_tokens, int batch, int num_k_heads, int num_v_heads,
    int max_slots, int k_dim, int v_dim, float q_scale, bool normalize_qk,
    topsStream_t stream) {
  auto q_sv = croq::make_spanview<3, croq::bf16>(
      (croq::bf16*)q, {(size_t)total_tokens, (size_t)num_k_heads, (size_t)k_dim});
  auto k_sv = croq::make_spanview<3, croq::bf16>(
      (croq::bf16*)k, {(size_t)total_tokens, (size_t)num_k_heads, (size_t)k_dim});
  auto v_sv = croq::make_spanview<3, croq::bf16>(
      (croq::bf16*)v, {(size_t)total_tokens, (size_t)num_v_heads, (size_t)v_dim});
  auto g_sv = croq::make_spanview<2, croq::bf16>(
      (croq::bf16*)g, {(size_t)total_tokens, (size_t)num_v_heads});
  auto beta_sv = croq::make_spanview<2, croq::bf16>(
      (croq::bf16*)beta, {(size_t)total_tokens, (size_t)num_v_heads});
  auto state_sv = croq::make_spanview<4, float>(
      state, {(size_t)max_slots, (size_t)num_v_heads, (size_t)k_dim, (size_t)v_dim});
  auto slots_sv = croq::make_spanview<1, croq::s64>(
      (croq::s64*)slots, {(size_t)batch});
  auto out_sv = croq::make_spanview<3, croq::bf16>(
      (croq::bf16*)out, {(size_t)total_tokens, (size_t)num_v_heads, (size_t)v_dim});
  auto cu_sv = croq::make_spanview<1, unsigned int>(
      cu_seqlens, {(size_t)(batch + 1)});
  gdn_recurrence_varlen_bf16(
      q_sv, k_sv, v_sv, g_sv, beta_sv, state_sv, slots_sv, out_sv, cu_sv,
      q_scale, normalize_qk ? 1u : 0u, stream);
}
