// Copyright 2025 LancerLab. All Rights Reserved.
// Licensed under the Apache License, Version 2.0.
// SPDX-License-Identifier: Apache-2.0
//
// Generated by Choreo (https://github.com/LancerLab/croqtile.git)
// Source: candle-croq-gdn/kernels/gdn_rmsnorm.co
// Do not edit manually — regenerate with: choreo -gs -t topscc -arch=gcu300

#include <tops.h>
#include <tops/half.h>
#include <tops/bfloat.h>
#include <tops/tops_runtime.h>
#include <tops/topscc_types.h>
#include <tcle.h>
#include "choreo_runtime.h"

using namespace choreo;

using vf = __vector4 float;
using vb = __vector2 __bf16;

__co_device__ void gated_rmsnorm_vec_inplace(
    void* x_v, void* z_v, void* gamma_f32_v, float eps
) {
    __bf16* x_bf16 = (__bf16*)x_v;
    __bf16* z_bf16 = (__bf16*)z_v;
    float* gamma_f32 = (float*)gamma_f32_v;

    vb x_raw = *(vb*)x_bf16;
    vf xf = tcle::cvt<vf>(x_raw);

    vb z_raw = *(vb*)z_bf16;
    vf zf = tcle::cvt<vf>(z_raw);

    vf wf = *(vf*)gamma_f32;

    vf sq = xf * xf;
    float sum_sq = tops::vreduce_sum<float>(sq);
    float rstd = tcle::rsqrt(sum_sq / 128.0f + eps);
    vf rv = (vf)(rstd);

    vf normed = xf * rv * wf;
    vf silu_z = zf * tcle::sigmoid(zf);
    vf result = silu_z * normed;

    *(vb*)x_bf16 = tcle::cvt<vb>(result);
}

__global__ void __choreo_device_gdn_gated_rmsnorm_bf16(choreo::bf16 * X, choreo::bf16 * Z, float * Gamma, choreo::bf16 * Out, unsigned DIM, unsigned ROWS, unsigned long mr_offset_gdn_gated_rmsnorm_bf16_paraby_0_paraby_1_l_gamma_f32, unsigned long mr_offset_gdn_gated_rmsnorm_bf16_paraby_0_paraby_1_l_x, unsigned long mr_offset_gdn_gated_rmsnorm_bf16_paraby_0_paraby_1_l_z) {
  choreo::choreo_sdte __choreo_dte_pool__[3];
  for (int __i = 0; __i < 3; ++__i) __choreo_dte_pool__[__i].init();
  { // parallel-by
  __local__ __valigned__ unsigned char anon_0[1572352];
  int sip_id = __tops_tid_x() * 2 + __tops_bid_x();
  int rows_per_sip = ((ROWS + 23) / 24);
  float* l_gamma_f32 = (float*)(anon_0 + mr_offset_gdn_gated_rmsnorm_bf16_paraby_0_paraby_1_l_gamma_f32);
  choreo::future lg(__choreo_dte_pool__[0], "lg", 71, 14, l_gamma_f32);
  tops::mdspan __mds0_Gamma(tops::Global, (float*)Gamma, DIM);
  tops::mdspan __mds1_l_gamma_f32(tops::Private, (float*)l_gamma_f32, DIM);
  tops::event lg__event__ = tops::memcpy_async(*lg.get_ctx(), __mds1_l_gamma_f32, __mds0_Gamma);
  lg.set_event(lg__event__);
  lg.wait();
  choreo::bfloat16* l_x = (choreo::bfloat16*)(anon_0 + mr_offset_gdn_gated_rmsnorm_bf16_paraby_0_paraby_1_l_x);
  choreo::bfloat16* l_z = (choreo::bfloat16*)(anon_0 + mr_offset_gdn_gated_rmsnorm_bf16_paraby_0_paraby_1_l_z);
  {
    int __iv_row_idx__elem__0 = 0;
    for (__iv_row_idx__elem__0 = 0; __iv_row_idx__elem__0 < rows_per_sip; ++__iv_row_idx__elem__0) {
      int row = (rows_per_sip * sip_id) + __iv_row_idx__elem__0;
      if ((row < ROWS)) {
        choreo::future lx(__choreo_dte_pool__[1], "lx", 80, 22, l_x);
        tops::mdspan __mds2_X(tops::Global, (choreo::bfloat16*)X, ROWS, DIM);
        tops::mdspan __mds3_l_x(tops::Private, (choreo::bfloat16*)l_x, 1, DIM);
        int __slice_offset0__X_2_l_x[] = {(int)(row), 0};
        tops::event lx__event__ = tops::slice_async(*lx.get_ctx(), __mds3_l_x, __mds2_X, __slice_offset0__X_2_l_x);
        lx.set_event(lx__event__);
        choreo::future lz(__choreo_dte_pool__[2], "lz", 81, 22, l_z);
        tops::mdspan __mds4_Z(tops::Global, (choreo::bfloat16*)Z, ROWS, DIM);
        tops::mdspan __mds5_l_z(tops::Private, (choreo::bfloat16*)l_z, 1, DIM);
        int __slice_offset1__Z_2_l_z[] = {(int)(row), 0};
        tops::event lz__event__ = tops::slice_async(*lz.get_ctx(), __mds5_l_z, __mds4_Z, __slice_offset1__Z_2_l_z);
        lz.set_event(lz__event__);
        lx.wait();
        lz.wait();
        gated_rmsnorm_vec_inplace((choreo::bf16*)l_x, (choreo::bf16*)l_z, (float*)l_gamma_f32, 0.000001f);
        choreo::future __choreo_anon_fut__0(__choreo_dte_pool__[0], "", 86, 17);
        tops::mdspan __mds6_l_x(tops::Private, (choreo::bfloat16*)l_x, 1, DIM);
        tops::mdspan __mds7_Out(tops::Global, (choreo::bfloat16*)Out, ROWS, DIM);
        int __deslice_offset0__Out_2_l_x[] = {(int)(row), 0};
        tops::deslice(*__choreo_anon_fut__0.get_ctx(), __mds7_Out, __mds6_l_x, __deslice_offset0__Out_2_l_x);
      }
      __syncthreads();
    }
    __iv_row_idx__elem__0 = 0;
  }
  }
}

void gdn_gated_rmsnorm_bf16(const choreo::spanned_view<choreo::bf16, 2> & X, const choreo::spanned_view<choreo::bf16, 2> & Z, const choreo::spanned_view<choreo::f32, 1> & Gamma, const choreo::spanned_view<choreo::bf16, 2> & Out, choreo::stream_t _s) {
  auto &DIM = X.shape()[1];
  auto &ROWS = X.shape()[0];
  choreo::runtime_check(X.shape()[1] == Z.shape()[1], "The shapes of the 1st parameter (dim: 1) and the 2nd parameter (dim: 1) are inconsistent.");
  choreo::runtime_check(Z.shape()[1] == Gamma.shape()[0], "The shapes of the 2nd parameter (dim: 1) and the 3rd parameter (dim: 0) are inconsistent.");
  choreo::runtime_check(Gamma.shape()[0] == Out.shape()[1], "The shapes of the 3rd parameter (dim: 0) and the 4th parameter (dim: 1) are inconsistent.");
  choreo::runtime_check(X.shape()[0] == Z.shape()[0], "The shapes of the 1st parameter (dim: 0) and the 2nd parameter (dim: 0) are inconsistent.");
  choreo::runtime_check(Z.shape()[0] == Out.shape()[0], "The shapes of the 2nd parameter (dim: 0) and the 4th parameter (dim: 0) are inconsistent.");

  choreo::runtime_check((static_cast<long long>(DIM) * 4LL < 4294967296LL), "The size of data transferred by DMA cannot exceed 2^32., 71.14");
  choreo::runtime_check((static_cast<long long>(DIM) * 4LL < 4294967296LL), "The size of data transferred by DMA cannot exceed 2^32., 71.14");
  choreo::runtime_check((static_cast<long long>(DIM) * 2LL < 4294967296LL), "The size of data transferred by DMA cannot exceed 2^32., 80.22");
  choreo::runtime_check((static_cast<long long>(DIM) < 16777216LL), "On GCU300, must satisfy: the 2nd dim ::gdn_gated_rmsnorm_bf16::DIM < 16777216., 80.37");
  choreo::runtime_check((static_cast<long long>(DIM) < 16777216LL), "On GCU300, must satisfy: the 2nd dim ::gdn_gated_rmsnorm_bf16::DIM < 16777216., 80.69");
  choreo::runtime_check((static_cast<long long>(DIM) * 2LL < 4294967296LL), "The size of data transferred by DMA cannot exceed 2^32., 81.22");
  choreo::runtime_check((static_cast<long long>(DIM) < 16777216LL), "On GCU300, must satisfy: the 2nd dim ::gdn_gated_rmsnorm_bf16::DIM < 16777216., 81.37");
  choreo::runtime_check((static_cast<long long>(DIM) < 16777216LL), "On GCU300, must satisfy: the 2nd dim ::gdn_gated_rmsnorm_bf16::DIM < 16777216., 81.69");
  choreo::runtime_check((static_cast<long long>(DIM) * 2LL < 4294967296LL), "The size of data transferred by DMA cannot exceed 2^32., 86.17");
  choreo::runtime_check((static_cast<long long>(DIM) < 16777216LL), "On GCU300, must satisfy: the 2nd dim ::gdn_gated_rmsnorm_bf16::DIM < 16777216., 86.26");
  choreo::runtime_check((static_cast<long long>(DIM) < 16777216LL), "On GCU300, must satisfy: the 2nd dim ::gdn_gated_rmsnorm_bf16::DIM < 16777216., 86.33");
  HeapSimulator::Chunks __co__local_chunks;
  __co__local_chunks.push_back({static_cast<size_t>((DIM * 4)), {{5,20}}, "_gdn_gated_rmsnorm_bf16_paraby_0_paraby_1_l_gamma_f32"});
  __co__local_chunks.push_back({static_cast<size_t>((DIM * 2)), {{8,20}}, "_gdn_gated_rmsnorm_bf16_paraby_0_paraby_1_l_x"});
  __co__local_chunks.push_back({static_cast<size_t>((DIM * 2)), {{9,20}}, "_gdn_gated_rmsnorm_bf16_paraby_0_paraby_1_l_z"});
  HeapSimulator __co_local_heap_simulator;
  HeapSimulator::Result __co__local_result = __co_local_heap_simulator.Allocate(__co__local_chunks, 512);
  unsigned __co__local_spm_size = __co__local_result.heap_size;
  choreo::runtime_check(__co__local_spm_size <= (size_t)1572352, "In the memory reuse of dynamic shapes, the size of the initial local spm should not exceed the memory usage limit 1572352 bytes.");
  unsigned long __co__local_chunk_offsets[3];
  size_t __co__local_chunks_idx = 0;
  for (const auto& [buffer_id, offset] : __co__local_result.chunk_offsets)
    __co__local_chunk_offsets[__co__local_chunks_idx++] = offset;
  dim3 __gdn_gated_rmsnorm_bf16_gdims0(2, 1, 1);
  dim3 __gdn_gated_rmsnorm_bf16_bdims0(12, 1, 1);
  __choreo_device_gdn_gated_rmsnorm_bf16<<<__gdn_gated_rmsnorm_bf16_gdims0, __gdn_gated_rmsnorm_bf16_bdims0, 0, _s>>>(X.data(), Z.data(), Gamma.data(), Out.data(), DIM, ROWS, __co__local_chunk_offsets[0], __co__local_chunk_offsets[1], __co__local_chunk_offsets[2]);
}

extern "C" void gdn_gated_rmsnorm_bf16_wrapper(
    void* x, void* z, void* gamma, void* out,
    int rows, int dim, topsStream_t stream) {
  auto x_sv = croq::make_spanview<2, croq::bf16>(
      (croq::bf16*)x, {(size_t)rows, (size_t)dim});
  auto z_sv = croq::make_spanview<2, croq::bf16>(
      (croq::bf16*)z, {(size_t)rows, (size_t)dim});
  auto gamma_sv = croq::make_spanview<1, float>(
      (float*)gamma, {(size_t)dim});
  auto out_sv = croq::make_spanview<2, croq::bf16>(
      (croq::bf16*)out, {(size_t)rows, (size_t)dim});
  gdn_gated_rmsnorm_bf16(x_sv, z_sv, gamma_sv, out_sv, stream);
}
