// Copyright 2025 LancerLab. All Rights Reserved.
// Licensed under the Apache License, Version 2.0.
// SPDX-License-Identifier: Apache-2.0
//
// Generated by Choreo (https://github.com/LancerLab/croqtile.git)
// Source: candle-croq-gdn/kernels/gdn_recurrence.co
// Do not edit manually — regenerate with: choreo -gs -t topscc -arch=gcu300

#include <tops/tops_runtime.h>
#include <tcle.h>
#include "choreo_runtime.h"

using namespace choreo;

// GDN Gated Delta Rule Recurrence Kernel (bf16 only, acore-accelerated)
// THE CORE KERNEL — prefill recurrence with fixed-length sequences.
//   S_t = g_t * S_{t-1} + beta_t * k_t ⊗ (v_t - S_t^T @ k_t)
//   o_t = S_t^T @ q_t
// Device function uses acore::matmul for S^T@q, acore::convert for bf16↔f32.
//

#include <tops.h>
#include <tops/half.h>
#include <tops/bfloat.h>
#include <tops/tops_runtime.h>
#include <common/acore_op.h>
#include <common/convert.h>

#define BK_CONST 128
#define BV_CONST 128

// One timestep of the gated delta rule recurrence for a single head:
//   1. S = g * S                        (decay)
//   2. kv_delta = beta * (v - S^T @ k)  (the "delta" in gated delta rule)
//   3. S = S + outer(k, kv_delta)       (state update)
//   4. o = S^T @ q                      (output)
// state is [KD, VD] in f32. q,k,v are bf16 vectors.
__co_device__ void gdn_recurrence_step(
    float* state,
    void* q_v, void* k_v, void* v_v,
    float* g_ptr, float* beta_ptr,
    float* o_out,
    float* kv_outer_buf,
    float* update_buf,
    float* kq_f32,
    float* v_f32_buf,
    int k_dim, int v_dim
) {
    __bf16* q_f16 = (__bf16*)q_v;
    __bf16* k_f16 = (__bf16*)k_v;
    __bf16* v_f16 = (__bf16*)v_v;
    float g_val = g_ptr[0];
    float beta_val = beta_ptr[0];

    // Step 1: decay S
    for (int ki = 0; ki < k_dim; ++ki)
        for (int vi = 0; vi < v_dim; ++vi)
            state[ki * v_dim + vi] *= g_val;

    // Step 2: kv_delta = beta * (v - S^T @ k)
    float kv_delta[BV_CONST] __attribute__((aligned(256)));
    for (int vi = 0; vi < v_dim; ++vi) {
        float acc = 0.0f;
        for (int ki = 0; ki < k_dim; ++ki)
            acc += state[ki * v_dim + vi] * (float)k_f16[ki];
        kv_delta[vi] = beta_val * ((float)v_f16[vi] - acc);
    }

    // Step 3: S += outer(k, kv_delta)
    for (int ki = 0; ki < k_dim; ++ki) {
        float k_val = (float)k_f16[ki];
        for (int vi = 0; vi < v_dim; ++vi)
            state[ki * v_dim + vi] += k_val * kv_delta[vi];
    }

    // Step 4: o = S^T @ q
    acore::convert<float, __bf16>(kq_f32, q_f16, k_dim);
    acore::matmul<1, acore::MK_KN>(
        o_out, kq_f32, state, (float*)nullptr, (int*)nullptr,
        k_dim, v_dim, 0, 1, 0, 1, 0);
}

#define KD 128
#define VD 128
__global__ void __choreo_device_gdn_recurrence_bf16(choreo::bf16 * Q, choreo::bf16 * K, choreo::bf16 * V, float * G, float * Beta, float * State, float * Out, unsigned BH, unsigned SEQ) {
  choreo::choreo_sdte __choreo_dte_pool__[6];
  for (int __i = 0; __i < 6; ++__i) __choreo_dte_pool__[__i].init();
  { // parallel-by: 95.24
  __local__ __valigned__ unsigned char anon_0[135680];
  int sip_id = __tops_tid_x() * 2 + __tops_bid_x();
  int heads_per_sip = ((BH + 23) / 24);
  // with-in: 100.9
  {
    int __iv_head_idx__elem__0 = 0;
    // foreach: 100.9
    for (__iv_head_idx__elem__0 = 0; __iv_head_idx__elem__0 < heads_per_sip; ++__iv_head_idx__elem__0) {
      int bh = (heads_per_sip * sip_id) + __iv_head_idx__elem__0;
      // inthreads: 102.13
      if ((bh < BH)) {
        float* state_l__buf__ = (float*)(anon_0 + 0);
        choreo::future state_l(__choreo_dte_pool__[0], "state_l", 104, 27, state_l__buf__);
        tops::mdspan __mds0_State(tops::Global, (float*)State, BH, 128, 128);
        tops::mdspan __mds1_state_l__buf__(tops::Private, (float*)state_l__buf__, 1, 128, 128);
        int __slice_offset0__State_2_state_l__buf__[] = {(int)(bh), 0, 0};
        tops::event state_l__event__ = tops::slice_async(*state_l.get_ctx(), __mds1_state_l__buf__, __mds0_State, __slice_offset0__State_2_state_l__buf__);
        state_l.set_event(state_l__event__);
        float* kv_delta_l = (float*)(anon_0 + 131584);
        float* update_l = (float*)(anon_0 + 65536);
        float* kq_f32_l = (float*)(anon_0 + 131072);
        float* v_f32_l = (float*)(anon_0 + 132608);
        float* out_l = (float*)(anon_0 + 132096);
        state_l.wait();
        // with-in: 115.17
        {
          int __iv_t__elem__0 = 0;
          // foreach: 115.17
          for (__iv_t__elem__0 = 0; __iv_t__elem__0 < SEQ; ++__iv_t__elem__0) {
            choreo::bfloat16* q_l__buf__ = (choreo::bfloat16*)(anon_0 + 133632);
            choreo::future q_l(__choreo_dte_pool__[1], "q_l", 117, 27, q_l__buf__);
            tops::mdspan __mds2_Q(tops::Global, (choreo::bfloat16*)Q, BH, SEQ, 128);
            tops::mdspan __mds3_q_l__buf__(tops::Private, (choreo::bfloat16*)q_l__buf__, 1, 1, 128);
            int __slice_offset1__Q_2_q_l__buf__[] = {(int)(bh), (int)(__iv_t__elem__0), 0};
            tops::event q_l__event__ = tops::slice_async(*q_l.get_ctx(), __mds3_q_l__buf__, __mds2_Q, __slice_offset1__Q_2_q_l__buf__);
            q_l.set_event(q_l__event__);
            choreo::bfloat16* k_l__buf__ = (choreo::bfloat16*)(anon_0 + 133120);
            choreo::future k_l(__choreo_dte_pool__[2], "k_l", 118, 27, k_l__buf__);
            tops::mdspan __mds4_K(tops::Global, (choreo::bfloat16*)K, BH, SEQ, 128);
            tops::mdspan __mds5_k_l__buf__(tops::Private, (choreo::bfloat16*)k_l__buf__, 1, 1, 128);
            int __slice_offset2__K_2_k_l__buf__[] = {(int)(bh), (int)(__iv_t__elem__0), 0};
            tops::event k_l__event__ = tops::slice_async(*k_l.get_ctx(), __mds5_k_l__buf__, __mds4_K, __slice_offset2__K_2_k_l__buf__);
            k_l.set_event(k_l__event__);
            choreo::bfloat16* v_l__buf__ = (choreo::bfloat16*)(anon_0 + 134144);
            choreo::future v_l(__choreo_dte_pool__[3], "v_l", 119, 27, v_l__buf__);
            tops::mdspan __mds6_V(tops::Global, (choreo::bfloat16*)V, BH, SEQ, 128);
            tops::mdspan __mds7_v_l__buf__(tops::Private, (choreo::bfloat16*)v_l__buf__, 1, 1, 128);
            int __slice_offset3__V_2_v_l__buf__[] = {(int)(bh), (int)(__iv_t__elem__0), 0};
            tops::event v_l__event__ = tops::slice_async(*v_l.get_ctx(), __mds7_v_l__buf__, __mds6_V, __slice_offset3__V_2_v_l__buf__);
            v_l.set_event(v_l__event__);
            float* g_l__buf__ = (float*)(anon_0 + 135168);
            choreo::future g_l(__choreo_dte_pool__[4], "g_l", 120, 27, g_l__buf__);
            tops::mdspan __mds8_G(tops::Global, (float*)G, BH, SEQ);
            tops::mdspan __mds9_g_l__buf__(tops::Private, (float*)g_l__buf__, 1, 1);
            int __slice_offset4__G_2_g_l__buf__[] = {(int)(bh), (int)(__iv_t__elem__0)};
            tops::event g_l__event__ = tops::slice_async(*g_l.get_ctx(), __mds9_g_l__buf__, __mds8_G, __slice_offset4__G_2_g_l__buf__);
            g_l.set_event(g_l__event__);
            float* b_l__buf__ = (float*)(anon_0 + 134656);
            choreo::future b_l(__choreo_dte_pool__[5], "b_l", 121, 27, b_l__buf__);
            tops::mdspan __mds10_Beta(tops::Global, (float*)Beta, BH, SEQ);
            tops::mdspan __mds11_b_l__buf__(tops::Private, (float*)b_l__buf__, 1, 1);
            int __slice_offset5__Beta_2_b_l__buf__[] = {(int)(bh), (int)(__iv_t__elem__0)};
            tops::event b_l__event__ = tops::slice_async(*b_l.get_ctx(), __mds11_b_l__buf__, __mds10_Beta, __slice_offset5__Beta_2_b_l__buf__);
            b_l.set_event(b_l__event__);
            q_l.wait();
            k_l.wait();
            v_l.wait();
            g_l.wait();
            b_l.wait();
            gdn_recurrence_step((float*)state_l.data(), (choreo::bf16*)q_l.data(), (choreo::bf16*)k_l.data(), (choreo::bf16*)v_l.data(), (float*)g_l.data(), (float*)b_l.data(), (float*)out_l, (float*)kv_delta_l, (float*)update_l, (float*)kq_f32_l, (float*)v_f32_l, 128, 128);
            choreo::future __choreo_anon_fut__0(__choreo_dte_pool__[0], "", 132, 21);
            tops::mdspan __mds12_out_l(tops::Private, (float*)out_l, 1, 1, 128);
            tops::mdspan __mds13_Out(tops::Global, (float*)Out, BH, SEQ, 128);
            int __deslice_offset0__Out_2_out_l[] = {(int)(bh), (int)(__iv_t__elem__0), 0};
            tops::deslice(*__choreo_anon_fut__0.get_ctx(), __mds13_Out, __mds12_out_l, __deslice_offset0__Out_2_out_l);
          } // t__elem__0
          __iv_t__elem__0 = 0;
        }
        choreo::future __choreo_anon_fut__1(__choreo_dte_pool__[0], "", 136, 17);
        tops::mdspan __mds14_state_l(tops::Private, (float*)state_l.data(), 1, 128, 128);
        tops::mdspan __mds15_State(tops::Global, (float*)State, BH, 128, 128);
        int __deslice_offset1__State_2_state_l[] = {(int)(bh), 0, 0};
        tops::deslice(*__choreo_anon_fut__1.get_ctx(), __mds15_State, __mds14_state_l, __deslice_offset1__State_2_state_l);
      }
      __syncthreads(); // end inthreads
    } // head_idx__elem__0
    __iv_head_idx__elem__0 = 0;
  }
  } // end parallel-by
}

void gdn_recurrence_bf16(const choreo::spanned_view<choreo::bf16, 3> & Q, const choreo::spanned_view<choreo::bf16, 3> & K, const choreo::spanned_view<choreo::bf16, 3> & V, const choreo::spanned_view<choreo::f32, 2> & G, const choreo::spanned_view<choreo::f32, 2> & Beta, const choreo::spanned_view<choreo::f32, 3> & State, const choreo::spanned_view<choreo::f32, 3> & Out, choreo::stream_t _s) {
  auto &BH = Q.shape()[0];
  auto &SEQ = Q.shape()[1];

  dim3 __gdn_recurrence_bf16_gdims0(2, 1, 1);
  dim3 __gdn_recurrence_bf16_bdims0(12, 1, 1);
  __choreo_device_gdn_recurrence_bf16<<<__gdn_recurrence_bf16_gdims0, __gdn_recurrence_bf16_bdims0, 0, _s>>>(Q.data(), K.data(), V.data(), G.data(), Beta.data(), State.data(), Out.data(), BH, SEQ);
}

// === Wrapper: raw pointers → spanned_view ===
extern "C" void gdn_recurrence_bf16_wrapper(
    void* q, void* k, void* v,
    float* g, float* beta, float* state, float* out,
    int bh, int seq_len, int k_dim, int v_dim, topsStream_t stream) {
  auto q_sv = croq::make_spanview<3, croq::bf16>(
      (croq::bf16*)q, {(size_t)bh, (size_t)seq_len, (size_t)k_dim});
  auto k_sv = croq::make_spanview<3, croq::bf16>(
      (croq::bf16*)k, {(size_t)bh, (size_t)seq_len, (size_t)k_dim});
  auto v_sv = croq::make_spanview<3, croq::bf16>(
      (croq::bf16*)v, {(size_t)bh, (size_t)seq_len, (size_t)v_dim});
  auto g_sv = croq::make_spanview<2, float>(
      g, {(size_t)bh, (size_t)seq_len});
  auto beta_sv = croq::make_spanview<2, float>(
      beta, {(size_t)bh, (size_t)seq_len});
  auto state_sv = croq::make_spanview<3, float>(
      state, {(size_t)bh, (size_t)k_dim, (size_t)v_dim});
  auto out_sv = croq::make_spanview<3, float>(
      out, {(size_t)bh, (size_t)seq_len, (size_t)v_dim});
  gdn_recurrence_bf16(q_sv, k_sv, v_sv, g_sv, beta_sv, state_sv, out_sv, stream);
}
